CREATE TABLE IF NOT EXISTS `mango_pay_biz_order` (
  `id` bigint NOT NULL COMMENT '业务支付单ID',
  `app_code` varchar(64) NOT NULL COMMENT '应用编码',
  `merchant_order_no` varchar(128) NOT NULL COMMENT '商户业务单号',
  `subject` varchar(128) NOT NULL COMMENT '订单标题',
  `amount` bigint NOT NULL COMMENT '支付金额，单位分',
  `refunded_amount` bigint NOT NULL DEFAULT '0' COMMENT '已退款金额，单位分',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `status` varchar(32) NOT NULL COMMENT '业务单状态',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '标准创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '标准更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mango_pay_biz_order_merchant` (`tenant_id`,`app_code`,`merchant_order_no`),
  KEY `idx_mango_pay_biz_order_status_time` (`status`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支付业务单';

CREATE TABLE IF NOT EXISTS `mango_pay_payment_order` (
  `id` bigint NOT NULL COMMENT '支付单ID',
  `biz_order_id` bigint NOT NULL COMMENT '业务支付单ID',
  `channel_code` varchar(32) NOT NULL COMMENT '渠道编码',
  `channel_order_no` varchar(128) DEFAULT NULL COMMENT '渠道支付单号',
  `pay_method` varchar(32) NOT NULL COMMENT '支付方式',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `amount` bigint NOT NULL COMMENT '支付金额，单位分',
  `status` varchar(32) NOT NULL COMMENT '支付单状态',
  `material_type` varchar(32) NOT NULL COMMENT '支付材料类型',
  `material_content` varchar(512) NOT NULL COMMENT '支付材料内容',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '标准创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '标准更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mango_pay_payment_order_idempotency` (`biz_order_id`,`idempotency_key`),
  KEY `idx_mango_pay_payment_order_biz_status` (`biz_order_id`,`status`),
  KEY `idx_mango_pay_payment_order_channel` (`channel_code`,`channel_order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支付单';

CREATE TABLE IF NOT EXISTS `mango_pay_refund_order` (
  `id` bigint NOT NULL COMMENT '退款单ID',
  `biz_order_id` bigint NOT NULL COMMENT '业务支付单ID',
  `payment_order_id` bigint NOT NULL COMMENT '支付单ID',
  `merchant_refund_no` varchar(128) NOT NULL COMMENT '商户退款单号',
  `channel_refund_no` varchar(128) DEFAULT NULL COMMENT '渠道退款单号',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `refund_amount` bigint NOT NULL COMMENT '退款金额，单位分',
  `status` varchar(32) NOT NULL COMMENT '退款单状态',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '标准创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '标准更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mango_pay_refund_order_merchant` (`biz_order_id`,`merchant_refund_no`),
  UNIQUE KEY `uk_mango_pay_refund_order_idempotency` (`biz_order_id`,`idempotency_key`),
  KEY `idx_mango_pay_refund_order_status_time` (`status`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='退款单';

CREATE TABLE IF NOT EXISTS `mango_pay_notify_record` (
  `id` bigint NOT NULL COMMENT '通知记录ID',
  `notify_event_id` varchar(128) NOT NULL COMMENT '回调事件ID',
  `payment_order_id` bigint NOT NULL COMMENT '支付单ID',
  `channel_order_no` varchar(128) NOT NULL COMMENT '渠道支付单号',
  `raw_request` varchar(1024) DEFAULT NULL COMMENT '原始请求摘要',
  `verified` tinyint NOT NULL DEFAULT '0' COMMENT '验签结果：0-失败，1-成功',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '标准创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '标准更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mango_pay_notify_event` (`notify_event_id`),
  KEY `idx_mango_pay_notify_payment` (`payment_order_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支付通知记录';
