CREATE TABLE IF NOT EXISTS `payment_channel_query_record` (
  `id` bigint NOT NULL COMMENT '主键',
  `query_no` varchar(64) NOT NULL COMMENT '查单记录号',
  `pay_order_no` varchar(64) NOT NULL COMMENT '支付订单号',
  `channel_trade_no` varchar(128) DEFAULT NULL COMMENT '通道交易号',
  `payment_order_id` bigint NOT NULL COMMENT '支付订单ID',
  `business_order_id` bigint NOT NULL COMMENT '业务订单ID',
  `channel_id` bigint DEFAULT NULL COMMENT '支付通道ID',
  `contract_id` bigint DEFAULT NULL COMMENT '签约配置ID',
  `query_type` varchar(32) NOT NULL COMMENT '查单类型',
  `request_payload` varchar(1024) DEFAULT NULL COMMENT '查单请求摘要',
  `response_payload` varchar(2048) DEFAULT NULL COMMENT '查单响应摘要',
  `before_status` varchar(32) NOT NULL COMMENT '查单前状态',
  `channel_status` varchar(32) NOT NULL COMMENT '通道返回状态',
  `result_status` varchar(32) NOT NULL COMMENT '处理后状态',
  `process_result` varchar(64) NOT NULL COMMENT '处理结果',
  `process_message` varchar(512) DEFAULT NULL COMMENT '处理说明',
  `query_time` datetime NOT NULL COMMENT '查单时间',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_channel_query_no` (`query_no`),
  KEY `idx_payment_channel_query_order` (`tenant_id`, `pay_order_no`, `query_time`),
  KEY `idx_payment_channel_query_payment` (`tenant_id`, `payment_order_id`, `query_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支付通道主动查单记录';
