CREATE TABLE IF NOT EXISTS `payment_mango_pay_scenario_control` (
  `id` bigint NOT NULL COMMENT '主键',
  `control_no` varchar(64) NOT NULL COMMENT '场景控制编号',
  `channel_code` varchar(32) NOT NULL COMMENT '通道编码，仅支持 MANGO_PAY',
  `contract_id` bigint DEFAULT NULL COMMENT '签约配置ID；为空表示芒果支付全局控制',
  `scenario_type` varchar(32) NOT NULL COMMENT '场景类型：PAYMENT/PAYMENT_QUERY/REFUND/REFUND_QUERY/BILL/CALLBACK_DELAY',
  `scenario_code` varchar(64) DEFAULT NULL COMMENT '交易场景码',
  `bill_difference_type` varchar(32) DEFAULT NULL COMMENT '账单差异类型：AMOUNT_PLUS/AMOUNT_MINUS',
  `difference_amount` bigint DEFAULT NULL COMMENT '账单差异金额，单位分',
  `callback_delay_minutes` int DEFAULT NULL COMMENT '回调延迟分钟数',
  `effective_count` int NOT NULL DEFAULT '1' COMMENT '生效次数',
  `consumed_count` int NOT NULL DEFAULT '0' COMMENT '已消费次数',
  `status` varchar(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/CONSUMED/DISABLED',
  `consumed_at` datetime DEFAULT NULL COMMENT '最近消费时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_mango_pay_scenario_control_no` (`tenant_id`, `control_no`),
  KEY `idx_payment_mango_pay_scenario_next` (`tenant_id`, `channel_code`, `scenario_type`, `contract_id`, `status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='芒果支付异常场景控制';
