CREATE TABLE IF NOT EXISTS `payment_refund_approval` (
  `id` bigint NOT NULL COMMENT '主键',
  `approval_no` varchar(64) NOT NULL COMMENT '退款审批单号',
  `business_order_id` bigint NOT NULL COMMENT '业务订单ID',
  `payment_order_id` bigint NOT NULL COMMENT '原支付订单ID',
  `refund_order_id` bigint DEFAULT NULL COMMENT '审批通过后生成的退款订单ID',
  `biz_order_no` varchar(64) NOT NULL COMMENT '业务订单号',
  `biz_refund_no` varchar(64) NOT NULL COMMENT '业务退款单号',
  `app_id` varchar(64) NOT NULL COMMENT '支付应用AppId',
  `refund_amount` bigint NOT NULL COMMENT '退款金额，单位分',
  `reason` varchar(512) NOT NULL COMMENT '退款原因',
  `status` varchar(32) NOT NULL COMMENT '审批状态：PENDING、APPROVED、REJECTED',
  `applicant_id` bigint DEFAULT NULL COMMENT '申请人ID',
  `applicant_name` varchar(128) DEFAULT NULL COMMENT '申请人名称',
  `apply_time` datetime NOT NULL COMMENT '申请时间',
  `reviewer_id` bigint DEFAULT NULL COMMENT '审核人ID',
  `reviewer_name` varchar(128) DEFAULT NULL COMMENT '审核人名称',
  `review_reason` varchar(512) DEFAULT NULL COMMENT '审核说明',
  `review_time` datetime DEFAULT NULL COMMENT '审核时间',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_refund_approval_no` (`approval_no`),
  UNIQUE KEY `uk_payment_refund_approval_biz` (`tenant_id`, `app_id`, `biz_refund_no`, `del_flag`),
  KEY `idx_payment_refund_approval_payment` (`tenant_id`, `payment_order_id`, `status`),
  KEY `idx_payment_refund_approval_status` (`tenant_id`, `status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='后台退款审批';
