CREATE TABLE IF NOT EXISTS `payment_offline_collection` (
  `id` bigint NOT NULL COMMENT '主键',
  `offline_collection_no` varchar(64) NOT NULL COMMENT '线下收款单号',
  `payment_order_id` bigint NOT NULL COMMENT '支付订单ID',
  `pay_order_no` varchar(64) NOT NULL COMMENT '支付订单号',
  `business_order_id` bigint NOT NULL COMMENT '业务订单ID',
  `biz_order_no` varchar(64) NOT NULL COMMENT '业务订单号',
  `channel_id` bigint DEFAULT NULL COMMENT '支付通道ID',
  `channel_code` varchar(32) NOT NULL COMMENT '支付通道编码',
  `contract_id` bigint DEFAULT NULL COMMENT '通道签约配置ID',
  `contract_capability_id` bigint DEFAULT NULL COMMENT '签约能力ID',
  `subject_id` bigint NOT NULL COMMENT '企业主体ID',
  `subject_name` varchar(128) NOT NULL COMMENT '企业主体名称',
  `bank_account_id` bigint DEFAULT NULL COMMENT '收款银行账户ID',
  `account_name` varchar(128) NOT NULL COMMENT '收款户名',
  `account_no_mask` varchar(128) NOT NULL COMMENT '脱敏收款账号',
  `bank_name` varchar(128) NOT NULL COMMENT '开户行',
  `amount` bigint NOT NULL COMMENT '收款金额，单位分',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `reconciliation_code` varchar(32) NOT NULL COMMENT '转账备注识别码',
  `transfer_remark` varchar(128) NOT NULL COMMENT '用户转账备注',
  `voucher_count` int NOT NULL DEFAULT '0' COMMENT '上传凭证数量',
  `collection_status` varchar(32) NOT NULL DEFAULT 'WAITING_TRANSFER' COMMENT '线下收款状态',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `confirmed_time` datetime DEFAULT NULL COMMENT '确认到账时间',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_offline_collection_no` (`tenant_id`, `offline_collection_no`, `del_flag`),
  UNIQUE KEY `uk_payment_offline_reconciliation_code` (`tenant_id`, `reconciliation_code`, `del_flag`),
  KEY `idx_payment_offline_collection_status_time` (`tenant_id`, `collection_status`, `created_at`),
  KEY `idx_payment_offline_collection_pay_order` (`tenant_id`, `pay_order_no`),
  KEY `idx_payment_offline_collection_biz_order` (`tenant_id`, `biz_order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='线下收款单';
