CREATE TABLE IF NOT EXISTS `payment_offline_refund_process` (
  `id` bigint NOT NULL COMMENT '主键',
  `offline_refund_no` varchar(64) NOT NULL COMMENT '线下退款单号',
  `offline_collection_id` bigint NOT NULL COMMENT '线下收款ID',
  `offline_collection_no` varchar(64) NOT NULL COMMENT '线下收款单号',
  `payment_order_id` bigint NOT NULL COMMENT '原支付订单ID',
  `pay_order_no` varchar(64) NOT NULL COMMENT '原支付订单号',
  `business_order_id` bigint NOT NULL COMMENT '业务订单ID',
  `biz_order_no` varchar(64) NOT NULL COMMENT '业务订单号',
  `channel_id` bigint DEFAULT NULL COMMENT '支付通道ID',
  `channel_code` varchar(32) NOT NULL COMMENT '支付通道编码',
  `refund_amount` bigint NOT NULL COMMENT '退款金额，单位分',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `refund_account_name` varchar(128) NOT NULL COMMENT '退款账户户名',
  `refund_account_no_mask` varchar(128) NOT NULL COMMENT '脱敏退款账号',
  `refund_bank_name` varchar(128) NOT NULL COMMENT '退款开户行',
  `refund_voucher_file_ids` varchar(512) NOT NULL COMMENT '退款凭证文件ID，多个用英文逗号分隔',
  `refund_voucher_count` int NOT NULL DEFAULT '0' COMMENT '退款凭证数量',
  `reason` varchar(512) NOT NULL COMMENT '退款原因',
  `remark` varchar(512) DEFAULT NULL COMMENT '退款备注',
  `refund_status` varchar(32) NOT NULL DEFAULT 'REFUNDED' COMMENT '线下退款状态',
  `refunded_time` datetime NOT NULL COMMENT '退款完成时间',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(128) DEFAULT NULL COMMENT '操作人名称',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_offline_refund_process_no` (`tenant_id`, `offline_refund_no`, `del_flag`),
  KEY `idx_payment_offline_refund_process_collection` (`tenant_id`, `offline_collection_id`, `refund_status`),
  KEY `idx_payment_offline_refund_process_payment` (`tenant_id`, `payment_order_id`, `refund_status`),
  KEY `idx_payment_offline_refund_process_business` (`tenant_id`, `business_order_id`, `refund_status`),
  KEY `idx_payment_offline_refund_process_status_time` (`tenant_id`, `refund_status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='线下退款处理记录';
