CREATE TABLE IF NOT EXISTS `payment_offline_bank_statement_batch` (
  `id` bigint NOT NULL COMMENT '主键',
  `batch_no` varchar(64) NOT NULL COMMENT '线下银行流水导入批次号',
  `bank_account_no_mask` varchar(128) DEFAULT NULL COMMENT '脱敏收款账号',
  `bank_name` varchar(128) DEFAULT NULL COMMENT '收款开户行',
  `statement_file_id` bigint DEFAULT NULL COMMENT '银行流水文件ID',
  `statement_file_name` varchar(255) NOT NULL COMMENT '银行流水文件名',
  `file_digest` varchar(128) NOT NULL COMMENT '银行流水文件摘要',
  `total_count` int NOT NULL DEFAULT '0' COMMENT '导入总笔数',
  `matched_count` int NOT NULL DEFAULT '0' COMMENT '匹配笔数',
  `confirmed_count` int NOT NULL DEFAULT '0' COMMENT '确认笔数',
  `difference_count` int NOT NULL DEFAULT '0' COMMENT '差异笔数',
  `batch_status` varchar(32) NOT NULL COMMENT '批次状态',
  `importer_id` bigint DEFAULT NULL COMMENT '导入人ID',
  `importer_name` varchar(128) DEFAULT NULL COMMENT '导入人名称',
  `import_time` datetime NOT NULL COMMENT '导入时间',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_offline_bank_statement_batch_no` (`tenant_id`, `batch_no`, `del_flag`),
  UNIQUE KEY `uk_payment_offline_bank_statement_file` (`tenant_id`, `file_digest`, `del_flag`),
  KEY `idx_payment_offline_bank_statement_status_time` (`tenant_id`, `batch_status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='线下收款银行流水导入批次';

CREATE TABLE IF NOT EXISTS `payment_offline_bank_statement_item` (
  `id` bigint NOT NULL COMMENT '主键',
  `batch_id` bigint NOT NULL COMMENT '导入批次ID',
  `batch_no` varchar(64) NOT NULL COMMENT '导入批次号',
  `row_no` int NOT NULL COMMENT 'Excel行号',
  `bank_statement_no` varchar(128) NOT NULL COMMENT '银行流水号',
  `bank_account_no_mask` varchar(128) DEFAULT NULL COMMENT '脱敏收款账号',
  `bank_name` varchar(128) DEFAULT NULL COMMENT '收款开户行',
  `trade_time` datetime NOT NULL COMMENT '银行交易时间',
  `trade_date` date NOT NULL COMMENT '银行交易日期',
  `amount` bigint NOT NULL COMMENT '收入金额，单位分',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `counterparty_name` varchar(128) DEFAULT NULL COMMENT '对方户名',
  `counterparty_account_no_mask` varchar(128) DEFAULT NULL COMMENT '脱敏对方账号',
  `summary` varchar(512) DEFAULT NULL COMMENT '银行摘要',
  `remark` varchar(512) DEFAULT NULL COMMENT '银行备注',
  `reconciliation_code` varchar(32) DEFAULT NULL COMMENT '解析出的转账备注识别码',
  `matched_offline_collection_id` bigint DEFAULT NULL COMMENT '匹配线下收款ID',
  `matched_offline_collection_no` varchar(64) DEFAULT NULL COMMENT '匹配线下收款单号',
  `matched_pay_order_no` varchar(64) DEFAULT NULL COMMENT '匹配支付订单号',
  `match_status` varchar(32) NOT NULL COMMENT '匹配状态',
  `match_message` varchar(512) NOT NULL COMMENT '匹配说明',
  `confirmed_time` datetime DEFAULT NULL COMMENT '确认时间',
  `confirmed_by` bigint DEFAULT NULL COMMENT '确认人ID',
  `confirmed_by_name` varchar(128) DEFAULT NULL COMMENT '确认人名称',
  `confirm_remark` varchar(512) DEFAULT NULL COMMENT '确认说明',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_offline_bank_statement_item_no` (`tenant_id`, `bank_account_no_mask`, `bank_statement_no`, `trade_date`, `del_flag`),
  KEY `idx_payment_offline_bank_statement_item_batch` (`tenant_id`, `batch_id`, `row_no`),
  KEY `idx_payment_offline_bank_statement_item_match` (`tenant_id`, `match_status`, `created_at`),
  KEY `idx_payment_offline_bank_statement_item_collection` (`tenant_id`, `matched_offline_collection_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='线下收款银行流水明细';

CREATE TABLE IF NOT EXISTS `payment_offline_collection_match` (
  `id` bigint NOT NULL COMMENT '主键',
  `offline_collection_id` bigint NOT NULL COMMENT '线下收款ID',
  `offline_collection_no` varchar(64) NOT NULL COMMENT '线下收款单号',
  `bank_statement_item_id` bigint NOT NULL COMMENT '银行流水明细ID',
  `bank_statement_no` varchar(128) NOT NULL COMMENT '银行流水号',
  `pay_order_no` varchar(64) NOT NULL COMMENT '支付订单号',
  `match_rule` varchar(64) NOT NULL COMMENT '匹配规则',
  `match_status` varchar(32) NOT NULL COMMENT '匹配状态',
  `difference_type` varchar(64) DEFAULT NULL COMMENT '差异类型',
  `match_message` varchar(512) NOT NULL COMMENT '匹配说明',
  `confirmed_time` datetime DEFAULT NULL COMMENT '确认时间',
  `confirmed_by` bigint DEFAULT NULL COMMENT '确认人ID',
  `confirmed_by_name` varchar(128) DEFAULT NULL COMMENT '确认人名称',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_offline_collection_match_item` (`tenant_id`, `bank_statement_item_id`, `del_flag`),
  KEY `idx_payment_offline_collection_match_collection` (`tenant_id`, `offline_collection_id`, `match_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='线下收款银行流水匹配结果';
