CREATE TABLE IF NOT EXISTS `payment_channel_bill_source` (
  `id` bigint NOT NULL COMMENT '主键',
  `contract_id` bigint NOT NULL COMMENT '签约通道ID',
  `channel_code` varchar(32) NOT NULL COMMENT '通道编码',
  `fetch_mode` varchar(16) NOT NULL COMMENT '获取方式：MANUAL/FTP/FTPS/HTTP',
  `endpoint` varchar(255) DEFAULT NULL COMMENT 'HTTP地址或FTP/FTPS服务器地址',
  `remote_path` varchar(255) DEFAULT NULL COMMENT 'FTP/FTPS远端路径',
  `credential_ref` varchar(255) DEFAULT NULL COMMENT '认证配置引用',
  `page_mode` varchar(32) DEFAULT NULL COMMENT 'HTTP分页模式：PAGE/CURSOR',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用：1-启用，0-停用',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_bill_source_contract_mode` (`tenant_id`, `contract_id`, `fetch_mode`, `del_flag`),
  KEY `idx_payment_bill_source_tenant` (`tenant_id`, `channel_code`, `enabled`),
  KEY `idx_payment_bill_source_contract` (`tenant_id`, `contract_id`, `enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支付通道账单获取源配置';

CREATE TABLE IF NOT EXISTS `payment_channel_bill_fetch_batch` (
  `id` bigint NOT NULL COMMENT '主键',
  `source_id` bigint NOT NULL COMMENT '账单获取源ID',
  `batch_no` varchar(64) NOT NULL COMMENT '获取批次号',
  `reconciliation_id` bigint DEFAULT NULL COMMENT '对账批次ID',
  `channel_code` varchar(32) NOT NULL COMMENT '通道编码',
  `fetch_mode` varchar(16) NOT NULL COMMENT '获取方式',
  `bill_date` date NOT NULL COMMENT '账单日期',
  `request_start_time` datetime DEFAULT NULL COMMENT '请求开始时间',
  `request_end_time` datetime DEFAULT NULL COMMENT '请求结束时间',
  `request_cursor` varchar(128) DEFAULT NULL COMMENT '请求游标',
  `request_page` int DEFAULT NULL COMMENT '请求页码',
  `page_size` int DEFAULT NULL COMMENT '每页数量',
  `response_digest` varchar(128) DEFAULT NULL COMMENT '响应摘要',
  `total_count` int NOT NULL DEFAULT '0' COMMENT '获取明细数',
  `fetch_status` varchar(32) NOT NULL COMMENT '获取状态：SUCCESS/FAILED',
  `fetch_result` varchar(512) DEFAULT NULL COMMENT '获取结果',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(128) DEFAULT NULL COMMENT '操作人名称',
  `fetch_start_time` datetime NOT NULL COMMENT '获取开始时间',
  `fetch_end_time` datetime DEFAULT NULL COMMENT '获取结束时间',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_bill_fetch_batch_no` (`tenant_id`, `batch_no`, `del_flag`),
  KEY `idx_payment_bill_fetch_source` (`tenant_id`, `source_id`, `bill_date`, `fetch_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支付通道账单获取批次';
