-- No-op by design.
-- FUIOU callback URLs are environment-specific signing configuration values.
-- They must be maintained through payment channel contract configuration,
-- not overwritten by formal Flyway migration.
