const noticePages = {
  'notice/business-config/index': () => import('./views/business-config/index.vue').then(m => m.default),
  'notice/message-definition/index': () => import('./views/business-config/index.vue').then(m => m.default),
  'notice/send-message/index': () => import('./views/send-message/index.vue').then(m => m.default),
  'notice/channel/index': () => import('./views/channel/index.vue').then(m => m.default),
  'notice/task/index': () => import('./views/task/index.vue').then(m => m.default),
  'notice/record/index': () => import('./views/record/index.vue').then(m => m.default),
  'notice/site-message/index': () => import('./views/site-message/index.vue').then(m => m.default),
  'notice/site/messages/index': () => import('./views/site-message/index.vue').then(m => m.default),
  'notice/setting/index': () => import('./views/setting/index.vue').then(m => m.default),
  'notice/receive-setting/index': () => import('./views/receive-setting/index.vue').then(m => m.default),
  'notice/retry/index': () => import('./views/retry/index.vue').then(m => m.default),
};

export const mangoNoticePageRegistry = {
  moduleCode: 'mango-notice',
  pages: noticePages,
};

export const mangoNoticeCapability = {
  moduleCode: 'mango-notice',
  packageName: '@mango/notice',
  capabilityCode: 'notice',
  capabilityName: '通知中心',
  requires: ['auth', 'rbac'],
  optional: [],
  backend: {
    moduleCode: 'mango-notice',
    menuSource: 'backend',
    resourceManifest: 'META-INF/mango/resource-manifest.json',
    requiredApis: ['/api/notice/business-config/page', '/api/notice/channels/page', '/api/notice/tasks/page'],
  },
  pages: [
    {
      component: 'notice/business-config/index',
      loader: noticePages['notice/business-config/index'],
      menuCode: 'notice:business',
      permissions: ['notice:business:view'],
    },
    {
      component: 'notice/message-definition/index',
      loader: noticePages['notice/message-definition/index'],
      menuCode: 'notice:message-definition',
      permissions: ['notice:business:view'],
    },
    {
      component: 'notice/send-message/index',
      loader: noticePages['notice/send-message/index'],
      menuCode: 'notice:send-message',
      permissions: ['notice:task:create'],
    },
    {
      component: 'notice/channel/index',
      loader: noticePages['notice/channel/index'],
      menuCode: 'notice:channel',
      permissions: ['notice:channel:view'],
    },
    {
      component: 'notice/task/index',
      loader: noticePages['notice/task/index'],
      menuCode: 'notice:task',
      permissions: ['notice:task:view'],
    },
    {
      component: 'notice/record/index',
      loader: noticePages['notice/record/index'],
      menuCode: 'notice:record',
      permissions: ['notice:record:view'],
    },
    {
      component: 'notice/site-message/index',
      loader: noticePages['notice/site-message/index'],
      menuCode: 'notice:site-message',
      permissions: ['notice:site:view'],
    },
    {
      component: 'notice/site/messages/index',
      loader: noticePages['notice/site/messages/index'],
      menuCode: 'notice:site-message',
      permissions: ['notice:site:view'],
    },
    {
      component: 'notice/setting/index',
      loader: noticePages['notice/setting/index'],
      menuCode: 'notice:setting',
      permissions: ['notice:setting:view'],
    },
    {
      component: 'notice/receive-setting/index',
      loader: noticePages['notice/receive-setting/index'],
      menuCode: 'notice:receive-setting',
      permissions: ['notice:setting:view'],
    },
    {
      component: 'notice/retry/index',
      loader: noticePages['notice/retry/index'],
      menuCode: 'notice:retry',
      permissions: ['notice:record:view'],
    },
  ],
  menus: [
    {
      menuCode: 'notice:business',
      moduleCode: 'mango-notice',
      component: 'notice/business-config/index',
      permissions: ['notice:business:view'],
      source: 'backend',
    },
    {
      menuCode: 'notice:message-definition',
      moduleCode: 'mango-notice',
      component: 'notice/message-definition/index',
      permissions: ['notice:business:view'],
      source: 'backend',
    },
    {
      menuCode: 'notice:send-message',
      moduleCode: 'mango-notice',
      component: 'notice/send-message/index',
      permissions: ['notice:task:create'],
      source: 'backend',
    },
    {
      menuCode: 'notice:channel',
      moduleCode: 'mango-notice',
      component: 'notice/channel/index',
      permissions: ['notice:channel:view'],
      source: 'backend',
    },
    {
      menuCode: 'notice:task',
      moduleCode: 'mango-notice',
      component: 'notice/task/index',
      permissions: ['notice:task:view'],
      source: 'backend',
    },
    {
      menuCode: 'notice:record',
      moduleCode: 'mango-notice',
      component: 'notice/record/index',
      permissions: ['notice:record:view'],
      source: 'backend',
    },
    {
      menuCode: 'notice:site-message',
      moduleCode: 'mango-notice',
      component: 'notice/site-message/index',
      permissions: ['notice:site:view'],
      source: 'backend',
    },
    {
      menuCode: 'notice:setting',
      moduleCode: 'mango-notice',
      component: 'notice/setting/index',
      permissions: ['notice:setting:view'],
      source: 'backend',
    },
    {
      menuCode: 'notice:receive-setting',
      moduleCode: 'mango-notice',
      component: 'notice/receive-setting/index',
      permissions: ['notice:setting:view'],
      source: 'backend',
    },
    {
      menuCode: 'notice:retry',
      moduleCode: 'mango-notice',
      component: 'notice/retry/index',
      permissions: ['notice:record:view'],
      source: 'backend',
    },
  ],
  permissions: [
    'notice:business:view',
    'notice:task:create',
    'notice:channel:view',
    'notice:task:view',
    'notice:record:view',
    'notice:site:view',
    'notice:setting:view',
  ],
  styles: [],
  runtime: {
    modes: ['local', 'micro', 'mixed'],
    defaultMode: 'local',
  },
  e2e: {
    smoke: ['notice-site-message'],
    screenshots: ['notice-site-message', 'notice-channel', 'notice-task'],
    dataChecks: ['notice-channel-page', 'notice-task-page'],
  },
};
