package io.mango.payment.core.service;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Objects;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class PaymentVirtualChannelPaymentUniqueConstraintMigrationTest {

    @Test
    @DisplayName("virtual channel payment migration should enforce one payment per payment order")
    void migration_containsPayOrderUniqueConstraint() throws IOException {
        String ddl;
        try (InputStream input = Objects.requireNonNull(getClass().getResourceAsStream(
                "/db/migration/payment/V62__payment_virtual_payment_pay_order_unique.sql"))) {
            ddl = new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }

        assertThat(ddl).contains("UNIQUE KEY `uk_payment_virtual_pay_order` (`tenant_id`, `pay_order_no`)");
    }

    @Test
    @DisplayName("virtual channel payment table should reject duplicate payment order submissions")
    void databaseConstraint_rejectsDuplicatePayOrderSubmission() {
        SingleConnectionDataSource dataSource = new SingleConnectionDataSource();
        dataSource.setUrl("jdbc:h2:mem:payment_virtual_unique_" + System.nanoTime()
                + ";MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE");
        dataSource.setUsername("sa");
        dataSource.setPassword("");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        createVirtualPaymentTable(jdbcTemplate);

        insertVirtualPayment(jdbcTemplate, 1L, "MP202606070001", "PO202606070001", "MCH202606070001");

        assertThatThrownBy(() -> insertVirtualPayment(
                jdbcTemplate,
                1L,
                "MP202606070002",
                "PO202606070001",
                "MCH202606070002"))
                .isInstanceOf(DuplicateKeyException.class);

        insertVirtualPayment(jdbcTemplate, 1L, "MP202606070003", "PO202606070002", "MCH202606070003");
        Long count = jdbcTemplate.queryForObject("select count(1) from payment_virtual_channel_payment", Long.class);
        assertThat(count).isEqualTo(2L);
    }

    private void createVirtualPaymentTable(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("""
                create table payment_virtual_channel_payment (
                  id bigint generated by default as identity primary key,
                  virtual_payment_no varchar(64) not null,
                  pay_order_no varchar(64),
                  channel_trade_no varchar(128),
                  tenant_id bigint not null,
                  unique key uk_payment_virtual_payment_no (virtual_payment_no),
                  unique key uk_payment_virtual_channel_trade (tenant_id, channel_trade_no),
                  unique key uk_payment_virtual_pay_order (tenant_id, pay_order_no)
                )
                """);
    }

    private void insertVirtualPayment(
            JdbcTemplate jdbcTemplate,
            Long tenantId,
            String virtualPaymentNo,
            String payOrderNo,
            String channelTradeNo) {
        jdbcTemplate.update("""
                insert into payment_virtual_channel_payment (
                  virtual_payment_no, pay_order_no, channel_trade_no, tenant_id
                ) values (?, ?, ?, ?)
                """,
                virtualPaymentNo,
                payOrderNo,
                channelTradeNo,
                tenantId);
    }
}
