package io.mango.plugin.baseline;

import org.apache.maven.plugin.MojoExecutionException;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.Collections;
import java.util.regex.Pattern;

final class MySqlBaselineStore {

    private static final Pattern AUTO_INCREMENT = Pattern.compile("(?i)\\s+AUTO_INCREMENT=\\d+");
    private static final Pattern DEFINER = Pattern.compile(
            "(?i)DEFINER\\s*=\\s*(?:`[^`]*`|[^@\\s]+)@(?:`[^`]*`|[^\\s]+)\\s*");
    private static final int INSERT_BATCH_SIZE = 250;

    private final MySqlJdbcUrl jdbcUrl;
    private final String username;
    private final String password;

    MySqlBaselineStore(String jdbcUrl, String username, String password)
            throws MojoExecutionException {
        this.jdbcUrl = MySqlJdbcUrl.parse(jdbcUrl);
        this.username = username;
        this.password = password;
    }

    DatabaseIdentity databaseIdentity(String database) throws MojoExecutionException {
        try (Connection connection = connect(database)) {
            DatabaseMetaData metadata = connection.getMetaData();
            String product = metadata.getDatabaseProductName();
            if (!product.toLowerCase(Locale.ROOT).contains("mysql")) {
                throw new MojoExecutionException(
                        "MANGO-BASELINE-014 only MySQL is supported, actual product=" + product);
            }
            return new DatabaseIdentity(product, metadata.getDatabaseProductVersion());
        } catch (SQLException exception) {
            throw databaseFailure("read database identity", exception);
        }
    }

    void createDatabase(String adminDatabase, String database) throws MojoExecutionException {
        validateDatabaseName(database);
        try (Connection connection = connect(adminDatabase);
                Statement statement = connection.createStatement()) {
            statement.execute("CREATE DATABASE " + quote(database)
                    + " CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci");
        } catch (SQLException exception) {
            throw databaseFailure("create temporary database " + database, exception);
        }
    }

    void dropDatabase(String adminDatabase, String database) throws MojoExecutionException {
        validateDatabaseName(database);
        try (Connection connection = connect(adminDatabase);
                Statement statement = connection.createStatement()) {
            statement.execute("DROP DATABASE IF EXISTS " + quote(database));
        } catch (SQLException exception) {
            throw databaseFailure("drop temporary database " + database, exception);
        }
    }

    String databaseUrl(String database) {
        return jdbcUrl.database(database);
    }

    String dumpModule(
            String database,
            String module,
            Set<String> groupModules,
            BaselineObjectOwnership ownership) throws MojoExecutionException {
        try (Connection connection = connect(database)) {
            DatabaseObjects objects = inspectObjects(connection, database);
            validateOwnership(objects, groupModules, ownership);

            StringBuilder sql = new StringBuilder(64_000);
            sql.append("-- mango:baseline-idempotent\n")
                    .append("-- generated by mango:baseline-generate; do not edit\n")
                    .append("SET FOREIGN_KEY_CHECKS=0;\n");

            List<String> moduleTables = objects.tables().entrySet().stream()
                    .filter(entry -> module.equals(ownership.tableOwner(entry.getKey())))
                    .map(Map.Entry::getValue)
                    .sorted(String.CASE_INSENSITIVE_ORDER)
                    .toList();
            for (String table : moduleTables) {
                sql.append(idempotentCreateTable(showCreateTable(connection, table))).append(";\n");
                appendTableData(connection, database, table, sql);
            }

            List<String> moduleViews = objects.views().entrySet().stream()
                    .filter(entry -> module.equals(ownership.viewOwner(entry.getKey())))
                    .map(Map.Entry::getValue)
                    .sorted(String.CASE_INSENSITIVE_ORDER)
                    .toList();
            for (String view : moduleViews) {
                sql.append(idempotentCreateView(
                        portableDefinition(showCreateView(connection, view), database))).append(";\n");
            }

            for (TriggerDefinition trigger : triggers(connection, database)) {
                String owner = ownership.tableOwner(trigger.tableName());
                if (module.equals(owner)) {
                    sql.append("DROP TRIGGER IF EXISTS ").append(quote(trigger.name())).append(";\n");
                    sql.append(portableDefinition(trigger.createStatement(), database)).append(";\n");
                }
            }
            sql.append("SET FOREIGN_KEY_CHECKS=1;\n");
            return sql.toString();
        } catch (SQLException exception) {
            throw databaseFailure("dump baseline for module " + module, exception);
        }
    }

    SchemaSnapshot snapshot(
            String database,
            Set<String> groupModules,
            BaselineObjectOwnership ownership) throws MojoExecutionException {
        try (Connection connection = connect(database)) {
            DatabaseObjects objects = inspectObjects(connection, database);
            validateOwnership(objects, groupModules, ownership);
            Map<String, String> definitions = new TreeMap<>();
            Map<String, List<List<String>>> data = new TreeMap<>();
            for (Map.Entry<String, String> table : objects.tables().entrySet()) {
                if (!groupModules.contains(ownership.tableOwner(table.getKey()))) {
                    continue;
                }
                definitions.put("table:" + table.getKey(),
                        normalizeDefinition(showCreateTable(connection, table.getValue()), database));
                data.put(table.getKey(), readHexRows(connection, database, table.getValue()));
            }
            for (Map.Entry<String, String> view : objects.views().entrySet()) {
                if (!groupModules.contains(ownership.viewOwner(view.getKey()))) {
                    continue;
                }
                definitions.put("view:" + view.getKey(),
                        normalizeDefinition(showCreateView(connection, view.getValue()), database));
            }
            for (TriggerDefinition trigger : triggers(connection, database)) {
                if (groupModules.contains(ownership.tableOwner(trigger.tableName()))) {
                    definitions.put("trigger:" + trigger.name().toLowerCase(Locale.ROOT),
                            normalizeDefinition(trigger.createStatement(), database));
                }
            }
            assertNoUnsupportedObjects(connection, database);
            return new SchemaSnapshot(Map.copyOf(definitions), Map.copyOf(data));
        } catch (SQLException exception) {
            throw databaseFailure("read schema snapshot from " + database, exception);
        }
    }

    private Connection connect(String database) throws SQLException {
        return DriverManager.getConnection(jdbcUrl.database(database), username, password);
    }

    private static DatabaseObjects inspectObjects(Connection connection, String database)
            throws SQLException {
        Map<String, String> tables = new TreeMap<>();
        Map<String, String> views = new TreeMap<>();
        try (PreparedStatement statement = connection.prepareStatement("""
                SELECT TABLE_NAME, TABLE_TYPE
                FROM information_schema.TABLES
                WHERE TABLE_SCHEMA = ?
                ORDER BY TABLE_NAME
                """)) {
            statement.setString(1, database);
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    String actualName = resultSet.getString(1);
                    String normalized = actualName.toLowerCase(Locale.ROOT);
                    if (isHistoryTable(normalized)) {
                        continue;
                    }
                    if ("VIEW".equalsIgnoreCase(resultSet.getString(2))) {
                        views.put(normalized, actualName);
                    } else {
                        tables.put(normalized, actualName);
                    }
                }
            }
        }
        return new DatabaseObjects(tables, views);
    }

    private static void validateOwnership(
            DatabaseObjects objects,
            Set<String> groupModules,
            BaselineObjectOwnership ownership) throws MojoExecutionException {
        Set<String> missing = new LinkedHashSet<>();
        for (String table : objects.tables().keySet()) {
            String owner = ownership.tableOwner(table);
            if (owner == null || !groupModules.contains(owner)) {
                missing.add("table:" + table);
            }
        }
        for (String view : objects.views().keySet()) {
            String owner = ownership.viewOwner(view);
            if (owner == null || !groupModules.contains(owner)) {
                missing.add("view:" + view);
            }
        }
        if (!missing.isEmpty()) {
            throw new MojoExecutionException(
                    "MANGO-BASELINE-015 database objects have no owner in this datasource group: "
                            + missing);
        }
    }

    private static String showCreateTable(Connection connection, String table) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery("SHOW CREATE TABLE " + quote(table))) {
            if (!resultSet.next()) {
                throw new SQLException("SHOW CREATE TABLE returned no row for " + table);
            }
            return resultSet.getString(2);
        }
    }

    private static String showCreateView(Connection connection, String view) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery("SHOW CREATE VIEW " + quote(view))) {
            if (!resultSet.next()) {
                throw new SQLException("SHOW CREATE VIEW returned no row for " + view);
            }
            return resultSet.getString(2);
        }
    }

    private static List<TriggerDefinition> triggers(Connection connection, String database)
            throws SQLException {
        List<TriggerDefinition> triggers = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement("""
                SELECT TRIGGER_NAME, EVENT_OBJECT_TABLE
                FROM information_schema.TRIGGERS
                WHERE TRIGGER_SCHEMA = ?
                ORDER BY TRIGGER_NAME
                """)) {
            statement.setString(1, database);
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    String name = resultSet.getString(1);
                    String table = resultSet.getString(2).toLowerCase(Locale.ROOT);
                    triggers.add(new TriggerDefinition(name, table, showCreateTrigger(connection, name)));
                }
            }
        }
        return triggers;
    }

    private static String showCreateTrigger(Connection connection, String trigger) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery("SHOW CREATE TRIGGER " + quote(trigger))) {
            if (!resultSet.next()) {
                throw new SQLException("SHOW CREATE TRIGGER returned no row for " + trigger);
            }
            ResultSetMetaData metadata = resultSet.getMetaData();
            for (int index = 1; index <= metadata.getColumnCount(); index++) {
                if ("SQL Original Statement".equalsIgnoreCase(metadata.getColumnLabel(index))) {
                    return resultSet.getString(index);
                }
            }
            return resultSet.getString(Math.min(3, metadata.getColumnCount()));
        }
    }

    private static void appendTableData(
            Connection connection,
            String database,
            String table,
            StringBuilder sql) throws SQLException {
        List<ColumnSpec> columns = insertableColumns(connection, database, table);
        if (columns.isEmpty()) {
            return;
        }
        List<List<String>> rows = readHexRows(connection, database, table, columns);
        for (int offset = 0; offset < rows.size(); offset += INSERT_BATCH_SIZE) {
            int end = Math.min(offset + INSERT_BATCH_SIZE, rows.size());
            sql.append("INSERT IGNORE INTO ").append(quote(table)).append(" (")
                    .append(columns.stream().map(ColumnSpec::name).map(MySqlBaselineStore::quote)
                            .reduce((a, b) -> a + ", " + b)
                            .orElseThrow())
                    .append(") VALUES\n");
            for (int rowIndex = offset; rowIndex < end; rowIndex++) {
                if (rowIndex > offset) {
                    sql.append(",\n");
                }
                sql.append("  (");
                List<String> row = rows.get(rowIndex);
                for (int columnIndex = 0; columnIndex < row.size(); columnIndex++) {
                    if (columnIndex > 0) {
                        sql.append(", ");
                    }
                    String hex = row.get(columnIndex);
                    sql.append(sqlLiteral(hex, columns.get(columnIndex)));
                }
                sql.append(')');
            }
            sql.append(";\n");
        }
    }

    private static List<List<String>> readHexRows(
            Connection connection,
            String database,
            String table) throws SQLException {
        return readHexRows(connection, database, table, insertableColumns(connection, database, table));
    }

    private static List<List<String>> readHexRows(
            Connection connection,
            String database,
            String table,
            List<ColumnSpec> columns) throws SQLException {
        if (columns.isEmpty()) {
            return List.of();
        }
        String expressions = columns.stream()
                .map(column -> "IF(" + quote(column.name()) + " IS NULL, NULL, HEX(CAST("
                        + quote(column.name()) + " AS BINARY)))")
                .reduce((a, b) -> a + ", " + b)
                .orElseThrow();
        List<List<String>> rows = new ArrayList<>();
        try (Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(
                        "SELECT " + expressions + " FROM " + quote(table))) {
            while (resultSet.next()) {
                List<String> row = new ArrayList<>(columns.size());
                for (int index = 1; index <= columns.size(); index++) {
                    row.add(resultSet.getString(index));
                }
                rows.add(Collections.unmodifiableList(row));
            }
        }
        rows.sort(MySqlBaselineStore::compareRows);
        return List.copyOf(rows);
    }

    private static List<ColumnSpec> insertableColumns(
            Connection connection,
            String database,
            String table) throws SQLException {
        List<ColumnSpec> columns = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement("""
                SELECT COLUMN_NAME, EXTRA, DATA_TYPE, CHARACTER_SET_NAME
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?
                ORDER BY ORDINAL_POSITION
                """)) {
            statement.setString(1, database);
            statement.setString(2, table);
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    String extra = resultSet.getString(2).toUpperCase(Locale.ROOT);
                    if (!extra.contains("GENERATED")) {
                        columns.add(new ColumnSpec(
                                resultSet.getString(1),
                                literalCharacterSet(resultSet.getString(3), resultSet.getString(4))));
                    }
                }
            }
        }
        return List.copyOf(columns);
    }

    private static String sqlLiteral(String hex, ColumnSpec column) {
        if (hex == null) {
            return "NULL";
        }
        String raw = "X'" + hex + "'";
        return column.literalCharacterSet() == null
                ? raw
                : "CONVERT(" + raw + " USING " + column.literalCharacterSet() + ")";
    }

    private static String literalCharacterSet(String dataType, String characterSet) {
        String normalizedType = dataType.toLowerCase(Locale.ROOT);
        if (Set.of(
                "binary",
                "varbinary",
                "tinyblob",
                "blob",
                "mediumblob",
                "longblob",
                "bit",
                "geometry").contains(normalizedType)) {
            return null;
        }
        if (characterSet != null && characterSet.matches("[a-zA-Z0-9_]+")) {
            return characterSet;
        }
        return "json".equals(normalizedType) ? "utf8mb4" : "ascii";
    }

    private static int compareRows(List<String> left, List<String> right) {
        for (int index = 0; index < left.size(); index++) {
            String leftValue = left.get(index);
            String rightValue = right.get(index);
            int comparison = Comparator.nullsFirst(String::compareTo).compare(leftValue, rightValue);
            if (comparison != 0) {
                return comparison;
            }
        }
        return 0;
    }

    private static String idempotentCreateTable(String statement) {
        return statement.replaceFirst("(?i)^CREATE\\s+TABLE\\s+", "CREATE TABLE IF NOT EXISTS ");
    }

    private static String idempotentCreateView(String statement) {
        return statement.replaceFirst("(?i)^CREATE\\s+", "CREATE OR REPLACE ");
    }

    private static String portableDefinition(String statement, String database) {
        String portable = DEFINER.matcher(statement).replaceAll("");
        return portable.replace("`" + database + "`.", "");
    }

    private static String normalizeDefinition(String statement, String database) {
        String portable = DEFINER.matcher(statement).replaceAll("");
        portable = AUTO_INCREMENT.matcher(portable).replaceAll("");
        portable = portable.replace("`" + database + "`.", "`${schema}`.");
        return portable.replaceAll("\\s+", " ").trim();
    }

    private static void assertNoUnsupportedObjects(Connection connection, String database)
            throws SQLException, MojoExecutionException {
        long routines = count(connection,
                "SELECT COUNT(*) FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA = ?", database);
        long events = count(connection,
                "SELECT COUNT(*) FROM information_schema.EVENTS WHERE EVENT_SCHEMA = ?", database);
        if (routines > 0 || events > 0) {
            throw new MojoExecutionException(
                    "MANGO-BASELINE-016 stored routines and events are not supported; routines="
                            + routines + ", events=" + events);
        }
    }

    private static long count(Connection connection, String sql, String database) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, database);
            try (ResultSet resultSet = statement.executeQuery()) {
                resultSet.next();
                return resultSet.getLong(1);
            }
        }
    }

    private static boolean isHistoryTable(String table) {
        return table.startsWith("flyway_schema_history_")
                || table.startsWith("flyway_baseline_verify_")
                || table.startsWith("flyway_baseline_reentry_");
    }

    private static String quote(String identifier) {
        return "`" + identifier.replace("`", "``") + "`";
    }

    private static void validateDatabaseName(String database) throws MojoExecutionException {
        if (database == null || !database.matches("[a-z][a-z0-9_]{0,63}")) {
            throw new MojoExecutionException(
                    "MANGO-BASELINE-017 unsafe temporary database name: " + database);
        }
    }

    private static MojoExecutionException databaseFailure(String action, SQLException exception) {
        return new MojoExecutionException(
                "MANGO-BASELINE-018 failed to " + action + ": " + exception.getMessage(), exception);
    }

    record DatabaseIdentity(String product, String version) {
    }

    record SchemaSnapshot(
            Map<String, String> definitions,
            Map<String, List<List<String>>> data) {
    }

    private record DatabaseObjects(Map<String, String> tables, Map<String, String> views) {
    }

    private record TriggerDefinition(String name, String tableName, String createStatement) {
    }

    private record ColumnSpec(String name, String literalCharacterSet) {
    }
}
