server:
  port: ${MANGO_SYSTEM_APP_PORT:18614}

spring:
  application:
    name: mango-system-capability-app

mango:
  module:
    module-service:
      modules:
        mango-identity:
          service-name: mango-identity-capability-app
        mango-resource:
          service-name: mango-resource-capability-app
