-- File module baseline for a fresh database. Flyway owns DDL only.

CREATE TABLE `file_storage_config` (
  `id` bigint NOT NULL COMMENT '存储配置ID',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户ID',
  `org_id` bigint DEFAULT NULL COMMENT '组织ID',
  `config_name` varchar(64) NOT NULL COMMENT '配置名称',
  `storage_type` varchar(32) NOT NULL COMMENT '存储类型',
  `endpoint` varchar(255) DEFAULT NULL COMMENT '接入地址',
  `public_endpoint` varchar(255) DEFAULT NULL COMMENT '公开访问地址',
  `region` varchar(64) DEFAULT NULL COMMENT '区域',
  `bucket_name` varchar(128) NOT NULL COMMENT '存储桶名称',
  `storage_path` varchar(255) NOT NULL DEFAULT '' COMMENT '存储路径前缀',
  `access_key` varchar(255) DEFAULT NULL COMMENT '访问密钥AccessKey',
  `secret_key` varchar(512) DEFAULT NULL COMMENT '访问密钥SecretKey',
  `path_style_access` tinyint NOT NULL DEFAULT '0' COMMENT '是否使用Path Style访问',
  `ssl_enabled` tinyint NOT NULL DEFAULT '0' COMMENT '是否启用HTTPS',
  `active` tinyint NOT NULL DEFAULT '0' COMMENT '是否默认启用',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '兼容创建时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '兼容更新时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_storage_config_name` (`tenant_id`,`config_name`),
  KEY `idx_file_storage_type` (`storage_type`),
  KEY `idx_file_storage_active` (`tenant_id`,`active`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件存储配置表';

CREATE TABLE `file_settings` (
  `id` bigint NOT NULL COMMENT '文件中心配置ID',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户ID',
  `org_id` bigint DEFAULT NULL COMMENT '组织ID',
  `max_size` bigint NOT NULL DEFAULT '104857600' COMMENT '单文件最大大小',
  `allowed_extensions` varchar(1000) DEFAULT NULL COMMENT '允许上传扩展名',
  `blocked_extensions` varchar(1000) DEFAULT 'exe,bat,cmd,sh,jar' COMMENT '禁止上传扩展名',
  `default_access_level` varchar(32) NOT NULL DEFAULT 'PRIVATE' COMMENT '默认访问级别',
  `duplicate_name_strategy` varchar(32) NOT NULL DEFAULT 'AUTO_RENAME' COMMENT '重名处理策略',
  `duplicate_check_directory_scoped` tinyint NOT NULL DEFAULT '1' COMMENT '是否按目录隔离重名',
  `object_name_strategy` varchar(32) NOT NULL DEFAULT 'DATE_UUID' COMMENT '对象命名策略',
  `instant_upload_enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用秒传',
  `instant_upload_scope` varchar(32) NOT NULL DEFAULT 'TENANT' COMMENT '秒传匹配范围',
  `content_type_check_enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否校验内容类型',
  `allowed_content_types` varchar(1000) DEFAULT NULL COMMENT '允许上传内容类型',
  `blocked_content_types` varchar(1000) DEFAULT 'application/x-msdownload,application/x-sh' COMMENT '禁止上传内容类型',
  `direct_upload_enabled` tinyint NOT NULL DEFAULT '0' COMMENT '是否启用客户端直传',
  `direct_upload_expire_seconds` bigint NOT NULL DEFAULT '900' COMMENT '直传签名有效期',
  `access_token_enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用访问令牌',
  `public_read_requires_token` tinyint NOT NULL DEFAULT '1' COMMENT '公开文件是否需要令牌',
  `access_mode` varchar(32) NOT NULL DEFAULT 'DIRECT' COMMENT '文件访问模式',
  `access_token_expire_seconds` bigint NOT NULL DEFAULT '86400' COMMENT '访问令牌有效期',
  `preview_provider_url` varchar(500) DEFAULT '/file-preview/files/preview' COMMENT '外部文档预览地址',
  `preview_expire_seconds` bigint NOT NULL DEFAULT '86400' COMMENT '预览访问有效期',
  `preview_external_extensions` varchar(1000) DEFAULT 'txt,csv,json,xml,png,jpg,jpeg,gif,webp,svg,pdf,ofd,doc,docx,xls,xlsx,ppt,pptx,odt,ods,odp,zip,rar,7z' COMMENT '外部预览扩展名',
  `archive_retain_enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否保留归档记录',
  `archive_retain_days` int NOT NULL DEFAULT '180' COMMENT '归档记录保留天数',
  `archive_restore_enabled` tinyint NOT NULL DEFAULT '0' COMMENT '是否允许恢复归档',
  `physical_delete_enabled` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除物理对象',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '兼容创建时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '兼容更新时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_settings_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件中心运行时配置表';

CREATE TABLE `file_directory` (
  `id` bigint NOT NULL COMMENT '目录ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `org_id` bigint DEFAULT NULL COMMENT '组织ID',
  `parent_id` bigint NOT NULL DEFAULT '0' COMMENT '父目录ID',
  `directory_name` varchar(128) NOT NULL COMMENT '目录名称',
  `directory_path` varchar(1000) NOT NULL DEFAULT '/' COMMENT '目录路径',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序值',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '兼容创建时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '兼容更新时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_directory_name` (`tenant_id`,`parent_id`,`directory_name`),
  KEY `idx_file_directory_parent` (`tenant_id`,`parent_id`,`sort`),
  KEY `idx_file_directory_path` (`tenant_id`,`directory_path`(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件逻辑目录表';

CREATE TABLE `file_object` (
  `id` bigint NOT NULL COMMENT '物理文件对象ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `org_id` bigint DEFAULT NULL COMMENT '组织ID',
  `storage_config_id` bigint DEFAULT NULL COMMENT '存储配置ID',
  `storage_type` varchar(32) NOT NULL COMMENT '存储类型',
  `bucket_name` varchar(128) NOT NULL COMMENT '存储桶名称',
  `object_name` varchar(500) NOT NULL COMMENT '对象名称',
  `file_hash` varchar(128) NOT NULL COMMENT '文件SHA-256哈希',
  `file_size` bigint NOT NULL COMMENT '文件大小',
  `content_type` varchar(128) DEFAULT NULL COMMENT '内容类型',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `ref_count` bigint NOT NULL DEFAULT '0' COMMENT '业务文件记录引用数',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '兼容创建时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '兼容更新时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_object_hash_storage` (`storage_config_id`,`bucket_name`,`file_hash`,`file_size`),
  KEY `idx_file_object_location` (`storage_config_id`,`bucket_name`,`object_name`),
  KEY `idx_file_object_hash` (`file_hash`,`file_size`),
  KEY `idx_file_object_status` (`tenant_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='物理文件对象表';

CREATE TABLE `file_hash_mapping` (
  `id` bigint NOT NULL COMMENT '秒传映射ID',
  `scope_type` varchar(32) NOT NULL COMMENT '秒传范围',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID，GLOBAL时为0',
  `org_id` bigint DEFAULT NULL COMMENT '组织ID',
  `storage_config_id` bigint DEFAULT NULL COMMENT '存储配置ID',
  `file_hash` varchar(128) NOT NULL COMMENT '文件SHA-256哈希',
  `file_size` bigint NOT NULL COMMENT '文件大小',
  `object_id` bigint NOT NULL COMMENT '物理文件对象ID',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '兼容创建时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '兼容更新时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_hash_mapping_target` (`scope_type`,`tenant_id`,`storage_config_id`,`file_hash`,`file_size`),
  KEY `idx_file_hash_mapping_object` (`object_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件秒传哈希映射表';

CREATE TABLE `file_record` (
  `id` bigint NOT NULL COMMENT '文件ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `org_id` bigint DEFAULT NULL COMMENT '组织ID',
  `biz_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `biz_id` varchar(128) DEFAULT NULL COMMENT '业务ID',
  `purpose` varchar(64) DEFAULT NULL COMMENT '文件用途',
  `biz_meta` json DEFAULT NULL COMMENT '业务自定义参数JSON',
  `directory_id` bigint NOT NULL DEFAULT '0' COMMENT '逻辑目录ID',
  `access_level` varchar(32) NOT NULL DEFAULT 'PRIVATE' COMMENT '访问级别',
  `object_id` bigint DEFAULT NULL COMMENT '物理文件对象ID',
  `storage_type` varchar(32) NOT NULL DEFAULT 'LOCAL' COMMENT '存储类型',
  `storage_config_id` bigint DEFAULT NULL COMMENT '存储配置ID',
  `bucket_name` varchar(128) NOT NULL DEFAULT 'local' COMMENT '存储桶名称',
  `object_name` varchar(500) NOT NULL COMMENT '对象名称',
  `file_name` varchar(255) NOT NULL COMMENT '原始文件名',
  `file_ext` varchar(32) DEFAULT NULL COMMENT '文件扩展名',
  `file_size` bigint NOT NULL DEFAULT '0' COMMENT '文件大小',
  `content_type` varchar(128) DEFAULT NULL COMMENT '内容类型',
  `file_hash` varchar(128) DEFAULT NULL COMMENT '文件哈希',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `archived` tinyint NOT NULL DEFAULT '0' COMMENT '是否归档',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '兼容创建时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '兼容更新时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_file_object` (`bucket_name`,`object_name`),
  KEY `idx_file_tenant` (`tenant_id`),
  KEY `idx_file_biz` (`tenant_id`,`biz_type`,`biz_id`),
  KEY `idx_file_purpose` (`tenant_id`,`purpose`),
  KEY `idx_file_record_object_id` (`object_id`),
  KEY `idx_file_status` (`tenant_id`,`status`,`archived`),
  KEY `idx_file_directory` (`tenant_id`,`directory_id`,`archived`,`created_time`),
  KEY `idx_file_created_time` (`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件记录表';

CREATE TABLE `file_upload_session` (
  `id` bigint NOT NULL COMMENT '上传会话ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `org_id` bigint DEFAULT NULL COMMENT '组织ID',
  `storage_config_id` bigint DEFAULT NULL COMMENT '存储配置ID',
  `storage_type` varchar(32) NOT NULL COMMENT '存储类型',
  `bucket_name` varchar(128) NOT NULL COMMENT '存储桶名称',
  `object_name` varchar(500) NOT NULL COMMENT '对象名称',
  `upload_mode` varchar(32) NOT NULL COMMENT '上传模式',
  `storage_upload_id` varchar(255) DEFAULT NULL COMMENT '存储上传ID',
  `file_name` varchar(255) NOT NULL COMMENT '原始文件名',
  `file_ext` varchar(32) DEFAULT NULL COMMENT '文件扩展名',
  `file_hash` varchar(128) NOT NULL COMMENT '文件SHA-256哈希',
  `file_size` bigint NOT NULL COMMENT '文件大小',
  `content_type` varchar(128) DEFAULT NULL COMMENT '内容类型',
  `chunk_size` bigint NOT NULL COMMENT '分片大小',
  `total_parts` int NOT NULL COMMENT '总分片数',
  `uploaded_parts` int NOT NULL DEFAULT '0' COMMENT '已上传分片数',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `expires_at` datetime NOT NULL COMMENT '过期时间',
  `purpose` varchar(64) DEFAULT NULL COMMENT '文件用途',
  `access_level` varchar(32) NOT NULL DEFAULT 'PRIVATE' COMMENT '访问级别',
  `biz_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `biz_id` varchar(128) DEFAULT NULL COMMENT '业务ID',
  `biz_meta` json DEFAULT NULL COMMENT '业务自定义参数JSON',
  `directory_id` bigint NOT NULL DEFAULT '0' COMMENT '逻辑目录ID',
  `object_id` bigint DEFAULT NULL COMMENT '物理文件对象ID',
  `file_record_id` bigint DEFAULT NULL COMMENT '文件记录ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '兼容创建时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '兼容更新时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_file_upload_session_tenant` (`tenant_id`,`status`),
  KEY `idx_file_upload_session_expires` (`expires_at`),
  KEY `idx_file_upload_session_hash` (`storage_config_id`,`file_hash`,`file_size`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件分片上传会话表';

CREATE TABLE `file_upload_part` (
  `id` bigint NOT NULL COMMENT '上传分片ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `org_id` bigint DEFAULT NULL COMMENT '组织ID',
  `session_id` bigint NOT NULL COMMENT '上传会话ID',
  `part_number` int NOT NULL COMMENT '分片序号',
  `part_size` bigint DEFAULT NULL COMMENT '分片大小',
  `part_hash` varchar(128) DEFAULT NULL COMMENT '分片哈希',
  `etag` varchar(255) DEFAULT NULL COMMENT '对象存储ETag',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '兼容创建时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '兼容更新时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_upload_part` (`session_id`,`part_number`),
  KEY `idx_file_upload_part_tenant` (`tenant_id`,`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件分片上传明细表';
