ALTER TABLE `notice_task`
  ADD COLUMN `message_scene` varchar(64) DEFAULT NULL COMMENT '系统消息场景' AFTER `channel_types`,
  ADD COLUMN `message_subject_type` varchar(64) DEFAULT NULL COMMENT '系统消息业务对象类型' AFTER `message_scene`,
  ADD COLUMN `message_subject_id` varchar(128) DEFAULT NULL COMMENT '系统消息业务对象 ID' AFTER `message_subject_type`,
  ADD COLUMN `message_subject_name` varchar(128) DEFAULT NULL COMMENT '系统消息业务对象名称快照' AFTER `message_subject_id`,
  ADD COLUMN `message_target_type` varchar(32) DEFAULT NULL COMMENT '系统消息跳转目标类型' AFTER `message_subject_name`,
  ADD COLUMN `message_target_key` varchar(128) DEFAULT NULL COMMENT '系统消息命名目标键' AFTER `message_target_type`,
  ADD COLUMN `message_target_params_json` text DEFAULT NULL COMMENT '系统消息目标参数 JSON' AFTER `message_target_key`,
  ADD COLUMN `message_target_open_mode` varchar(32) DEFAULT NULL COMMENT '系统消息跳转打开方式' AFTER `message_target_params_json`,
  ADD COLUMN `message_data_json` text DEFAULT NULL COMMENT '系统消息业务数据快照 JSON' AFTER `message_target_open_mode`,
  ADD COLUMN `message_actions_json` text DEFAULT NULL COMMENT '系统消息动作快照 JSON' AFTER `message_data_json`,
  ADD COLUMN `message_expire_time` datetime DEFAULT NULL COMMENT '系统消息过期时间' AFTER `message_actions_json`;

ALTER TABLE `notice_site_message`
  ADD COLUMN `message_scene` varchar(64) DEFAULT NULL COMMENT '系统消息场景' AFTER `content`,
  ADD COLUMN `subject_type` varchar(64) DEFAULT NULL COMMENT '业务对象类型' AFTER `message_scene`,
  ADD COLUMN `subject_id` varchar(128) DEFAULT NULL COMMENT '业务对象 ID' AFTER `subject_type`,
  ADD COLUMN `subject_name` varchar(128) DEFAULT NULL COMMENT '业务对象名称快照' AFTER `subject_id`,
  ADD COLUMN `target_type` varchar(32) DEFAULT NULL COMMENT '跳转目标类型' AFTER `subject_name`,
  ADD COLUMN `target_key` varchar(128) DEFAULT NULL COMMENT '命名目标键' AFTER `target_type`,
  ADD COLUMN `target_params_json` text DEFAULT NULL COMMENT '目标参数 JSON' AFTER `target_key`,
  ADD COLUMN `target_open_mode` varchar(32) DEFAULT NULL COMMENT '跳转打开方式' AFTER `target_params_json`,
  ADD COLUMN `data_json` text DEFAULT NULL COMMENT '业务数据快照 JSON' AFTER `target_open_mode`,
  ADD COLUMN `expire_time` datetime DEFAULT NULL COMMENT '消息过期时间' AFTER `data_json`,
  ADD KEY `idx_notice_site_subject` (`tenant_id`, `subject_type`, `subject_id`),
  ADD KEY `idx_notice_site_scene` (`tenant_id`, `message_scene`, `created_at`);

CREATE TABLE IF NOT EXISTS `notice_site_message_action` (
  `id` bigint NOT NULL COMMENT '主键',
  `message_id` bigint NOT NULL COMMENT '系统消息 ID',
  `action_code` varchar(64) NOT NULL COMMENT '动作编码',
  `action_label` varchar(64) NOT NULL COMMENT '动作展示名称',
  `interaction_type` varchar(32) NOT NULL DEFAULT 'EVENT' COMMENT '交互类型：EVENT、ROUTE',
  `event_type` varchar(128) DEFAULT NULL COMMENT '投递事件类型',
  `target_type` varchar(32) DEFAULT NULL COMMENT '动作跳转目标类型',
  `target_key` varchar(128) DEFAULT NULL COMMENT '动作命名目标键',
  `target_params_json` text DEFAULT NULL COMMENT '动作目标参数 JSON',
  `target_open_mode` varchar(32) DEFAULT NULL COMMENT '动作跳转打开方式',
  `confirm_required` tinyint NOT NULL DEFAULT 0 COMMENT '是否需要确认',
  `input_schema` text DEFAULT NULL COMMENT '输入 JSON Schema',
  `status` varchar(32) NOT NULL DEFAULT 'AVAILABLE' COMMENT '动作状态',
  `failure_reason` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `expire_time` datetime DEFAULT NULL COMMENT '动作过期时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_site_action_code` (`tenant_id`, `message_id`, `action_code`),
  KEY `idx_notice_site_action_message` (`tenant_id`, `message_id`, `status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统消息动作表';

CREATE TABLE IF NOT EXISTS `notice_site_message_action_request` (
  `id` bigint NOT NULL COMMENT '主键',
  `message_id` bigint NOT NULL COMMENT '系统消息 ID',
  `action_id` bigint NOT NULL COMMENT '系统消息动作 ID',
  `action_code` varchar(64) NOT NULL COMMENT '动作编码',
  `actor_user_id` bigint NOT NULL COMMENT '操作用户 ID',
  `request_id` varchar(160) NOT NULL COMMENT '动作请求 ID',
  `input_json` text DEFAULT NULL COMMENT '动作输入 JSON',
  `status` varchar(32) NOT NULL DEFAULT 'REQUESTED' COMMENT '请求状态',
  `fail_code` varchar(64) DEFAULT NULL COMMENT '失败码',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `result_json` text DEFAULT NULL COMMENT '业务处理结果 JSON',
  `event_id` varchar(64) DEFAULT NULL COMMENT '领域事件 ID',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `finished_at` datetime DEFAULT NULL COMMENT '完成时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_site_action_request` (`tenant_id`, `request_id`),
  KEY `idx_notice_site_action_request_message` (`tenant_id`, `message_id`, `action_code`, `actor_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统消息动作请求流水表';
