-- Fresh-install final schema for mango-notice. Flyway owns DDL only; data is managed by Mango Resource Registry.

CREATE TABLE IF NOT EXISTS `notice_announcement` (
  `id` bigint NOT NULL COMMENT '主键',
  `title` varchar(200) NOT NULL COMMENT '公告标题',
  `content` text NOT NULL COMMENT '公告内容',
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '公告状态：DRAFT、PUBLISHED、OFFLINE',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `valid_start_time` datetime DEFAULT NULL COMMENT '有效开始时间',
  `valid_end_time` datetime DEFAULT NULL COMMENT '有效结束时间',
  `pinned` tinyint NOT NULL DEFAULT '0' COMMENT '是否置顶',
  `confirm_required` tinyint NOT NULL DEFAULT '0' COMMENT '是否需要确认',
  `sync_message_enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否同步系统消息提醒',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_notice_announcement_status` (`tenant_id`,`status`,`publish_time`),
  KEY `idx_notice_announcement_valid` (`tenant_id`,`valid_start_time`,`valid_end_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知公告表';
CREATE TABLE IF NOT EXISTS `notice_announcement_recipient` (
  `id` bigint NOT NULL COMMENT '主键',
  `announcement_id` bigint NOT NULL COMMENT '公告 ID',
  `user_id` bigint NOT NULL COMMENT '接收用户 ID',
  `read_status` varchar(32) NOT NULL DEFAULT 'UNREAD' COMMENT '阅读状态',
  `read_time` datetime DEFAULT NULL COMMENT '阅读时间',
  `confirm_status` varchar(32) NOT NULL DEFAULT 'NOT_REQUIRED' COMMENT '确认状态',
  `confirm_time` datetime DEFAULT NULL COMMENT '确认时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_announcement_recipient` (`tenant_id`,`announcement_id`,`user_id`),
  KEY `idx_notice_announcement_user` (`tenant_id`,`user_id`,`read_status`,`created_at`),
  KEY `idx_notice_announcement_confirm` (`tenant_id`,`announcement_id`,`confirm_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知公告用户接收记录表';
CREATE TABLE IF NOT EXISTS `notice_announcement_target` (
  `id` bigint NOT NULL COMMENT '主键',
  `announcement_id` bigint NOT NULL COMMENT '公告 ID',
  `target_type` varchar(32) NOT NULL COMMENT '发布对象类型：ALL、ORG、ROLE、USER',
  `target_id` bigint DEFAULT NULL COMMENT '发布对象 ID',
  `target_name` varchar(128) DEFAULT NULL COMMENT '发布对象名称快照',
  `include_children` tinyint NOT NULL DEFAULT '0' COMMENT '组织是否包含下级',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_notice_announcement_target` (`tenant_id`,`announcement_id`),
  KEY `idx_notice_announcement_target_value` (`tenant_id`,`target_type`,`target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知公告发布对象快照表';
CREATE TABLE IF NOT EXISTS `notice_audit_log` (
  `id` bigint NOT NULL COMMENT '主键',
  `action_type` varchar(64) NOT NULL COMMENT '操作类型',
  `target_type` varchar(64) NOT NULL COMMENT '目标类型',
  `target_id` bigint DEFAULT NULL COMMENT '目标 ID',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人 ID',
  `audit_snapshot` text COMMENT '审计摘要',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_notice_audit_target` (`tenant_id`,`target_type`,`target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知审计日志表';
CREATE TABLE IF NOT EXISTS `notice_business_channel_template` (
  `id` bigint NOT NULL COMMENT '主键',
  `business_type_id` bigint NOT NULL COMMENT '业务类型 ID',
  `biz_type` varchar(64) NOT NULL COMMENT '业务类型编码快照',
  `channel_type` varchar(32) NOT NULL COMMENT '渠道类型',
  `template_name` varchar(128) DEFAULT NULL COMMENT '模板名称',
  `title_template` varchar(200) DEFAULT NULL COMMENT '标题模板',
  `content_template` text COMMENT '内容模板',
  `channel_template_id` varchar(128) DEFAULT NULL COMMENT '三方模板 ID',
  `variable_mapping` text COMMENT '变量映射 JSON',
  `version` int NOT NULL DEFAULT '1' COMMENT '版本号',
  `version_status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '版本状态',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `channel_config_id` bigint DEFAULT NULL COMMENT '绑定渠道配置 ID，空表示 AUTO',
  `route_mode` varchar(16) NOT NULL DEFAULT 'AUTO' COMMENT '路由模式：EXACT、TAG、AUTO',
  `route_tag_code` varchar(64) DEFAULT NULL COMMENT 'TAG 模式标签编码',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `publish_by` bigint DEFAULT NULL COMMENT '发布人 ID',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_biz_channel_version` (`tenant_id`,`biz_type`,`channel_type`,`version`),
  KEY `idx_notice_biz_channel_active` (`tenant_id`,`biz_type`,`channel_type`,`version_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知业务渠道模板表';
CREATE TABLE IF NOT EXISTS `notice_business_config_version` (
  `id` bigint NOT NULL COMMENT '主键',
  `business_type_id` bigint NOT NULL COMMENT '业务类型 ID',
  `biz_type` varchar(64) NOT NULL COMMENT '业务类型编码快照',
  `params_schema` text COMMENT '参数 schema JSON',
  `default_priority` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '默认优先级',
  `idempotent_strategy` varchar(64) DEFAULT NULL COMMENT '幂等策略',
  `version` int NOT NULL DEFAULT '1' COMMENT '版本号',
  `version_status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '版本状态',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `publish_by` bigint DEFAULT NULL COMMENT '发布人 ID',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_biz_config_version` (`tenant_id`,`biz_type`,`version`),
  KEY `idx_notice_biz_config_status` (`tenant_id`,`biz_type`,`version_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知业务发布配置版本表';
CREATE TABLE IF NOT EXISTS `notice_business_type` (
  `id` bigint NOT NULL COMMENT '主键',
  `biz_type` varchar(64) NOT NULL COMMENT '业务类型编码',
  `biz_name` varchar(128) NOT NULL COMMENT '业务类型名称',
  `biz_group` varchar(64) DEFAULT NULL COMMENT '业务分组',
  `domain_code` varchar(64) NOT NULL DEFAULT 'NOTICE' COMMENT '业务域编码',
  `description` varchar(500) DEFAULT NULL COMMENT '说明',
  `params_schema` text COMMENT '参数 schema JSON',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `default_priority` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '默认优先级',
  `idempotent_strategy` varchar(64) DEFAULT NULL COMMENT '幂等策略',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_biz_type` (`tenant_id`,`biz_type`),
  KEY `idx_notice_biz_group` (`tenant_id`,`biz_group`),
  KEY `idx_notice_business_type_domain` (`tenant_id`,`domain_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知业务类型表';
CREATE TABLE IF NOT EXISTS `notice_callback_log` (
  `id` bigint NOT NULL COMMENT '主键',
  `channel_type` varchar(32) NOT NULL COMMENT '渠道类型',
  `provider_message_id` varchar(128) DEFAULT NULL COMMENT '供应商消息 ID',
  `callback_snapshot` text COMMENT '回调摘要',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  PRIMARY KEY (`id`),
  KEY `idx_notice_callback_provider` (`tenant_id`,`provider_message_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知回调日志表';
CREATE TABLE IF NOT EXISTS `notice_channel_config` (
  `id` bigint NOT NULL COMMENT '主键',
  `config_code` varchar(64) NOT NULL COMMENT '渠道配置稳定编码',
  `channel_type` varchar(32) NOT NULL COMMENT '渠道类型',
  `provider_code` varchar(64) DEFAULT NULL COMMENT '供应商编码',
  `config_name` varchar(128) DEFAULT NULL COMMENT '配置名称',
  `config_json` text COMMENT '非敏感配置 JSON',
  `secret_refs_json` text COMMENT 'Resource Secret 引用 JSON',
  `secret_config_json` text COMMENT '环境人工补录 Secret JSON',
  `resource_id` varchar(128) DEFAULT NULL COMMENT 'Resource 声明 ID',
  `resource_version` int DEFAULT NULL COMMENT 'Resource 版本',
  `resource_module_code` varchar(64) DEFAULT NULL COMMENT 'Resource 模块编码',
  `resource_source` varchar(32) NOT NULL DEFAULT 'MANUAL' COMMENT '配置来源',
  `managed_fields_json` text COMMENT 'Resource 管理字段清单',
  `secret_status` varchar(32) NOT NULL DEFAULT 'NOT_REQUIRED' COMMENT 'Secret 完整性状态',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `priority` int NOT NULL DEFAULT '0' COMMENT '优先级',
  `weight` int NOT NULL DEFAULT '100' COMMENT 'AUTO 路由权重',
  `config_status` varchar(32) NOT NULL DEFAULT 'INCOMPLETE' COMMENT '配置状态',
  `last_send_status` varchar(32) NOT NULL DEFAULT 'NONE' COMMENT '最近发送状态',
  `last_send_time` datetime DEFAULT NULL COMMENT '最近发送时间',
  `last_failure_code` varchar(64) DEFAULT NULL COMMENT '最近失败码',
  `last_failure_reason` varchar(500) DEFAULT NULL COMMENT '最近失败原因',
  `rate_limit_config` text COMMENT '频控配置 JSON',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_channel_config_code` (`tenant_id`,`config_code`),
  KEY `idx_notice_channel_type` (`tenant_id`,`channel_type`,`enabled`),
  KEY `idx_notice_channel_route` (`tenant_id`,`channel_type`,`enabled`,`config_status`,`weight`),
  KEY `idx_notice_channel_source` (`tenant_id`,`resource_source`,`resource_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知渠道配置表';
CREATE TABLE IF NOT EXISTS `notice_channel_route_tag` (
  `id` bigint NOT NULL COMMENT '主键',
  `channel_type` varchar(32) NOT NULL COMMENT '渠道类型',
  `tag_code` varchar(64) NOT NULL COMMENT '标签稳定编码',
  `tag_name` varchar(128) NOT NULL COMMENT '标签名称',
  `description` varchar(500) DEFAULT NULL COMMENT '标签说明',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_channel_route_tag` (`tenant_id`,`channel_type`,`tag_code`),
  KEY `idx_notice_channel_route_tag_name` (`tenant_id`,`channel_type`,`tag_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知渠道路由标签表';
CREATE TABLE IF NOT EXISTS `notice_channel_config_route_tag` (
  `id` bigint NOT NULL COMMENT '主键',
  `channel_config_id` bigint NOT NULL COMMENT '渠道配置 ID',
  `route_tag_id` bigint NOT NULL COMMENT '路由标签 ID',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_channel_config_route_tag` (`tenant_id`,`channel_config_id`,`route_tag_id`),
  KEY `idx_notice_channel_route_tag_config` (`tenant_id`,`route_tag_id`,`channel_config_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知渠道配置路由标签关系表';
CREATE TABLE IF NOT EXISTS `notice_receive_preference` (
  `id` bigint NOT NULL COMMENT '主键',
  `user_id` bigint NOT NULL COMMENT '用户 ID',
  `scope_type` varchar(32) NOT NULL COMMENT '范围类型',
  `scope_value` varchar(128) NOT NULL DEFAULT '' COMMENT '范围值',
  `channel_type` varchar(32) DEFAULT NULL COMMENT '渠道类型，空表示总开关',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否接收',
  `account_id` bigint DEFAULT NULL COMMENT '指定接收账户 ID',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_receive_preference` (`tenant_id`,`user_id`,`scope_type`,`scope_value`,`channel_type`),
  KEY `idx_notice_receive_preference_user` (`tenant_id`,`user_id`,`scope_type`,`scope_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知接收偏好表';
CREATE TABLE IF NOT EXISTS `notice_recipient` (
  `id` bigint NOT NULL COMMENT '主键',
  `task_id` bigint NOT NULL COMMENT '任务 ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户 ID',
  `recipient_name` varchar(128) DEFAULT NULL COMMENT '接收人名称快照',
  `mobile` varchar(32) DEFAULT NULL COMMENT '手机号快照',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱快照',
  `wechat_openid` varchar(128) DEFAULT NULL COMMENT '微信 openid 快照',
  `wecom_user_id` varchar(128) DEFAULT NULL COMMENT '企业微信 userId 快照',
  `dingtalk_user_id` varchar(128) DEFAULT NULL COMMENT '钉钉 userId 快照',
  `external_id` varchar(128) DEFAULT NULL COMMENT '外部联系人标识',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_notice_recipient_task` (`task_id`),
  KEY `idx_notice_recipient_user` (`tenant_id`,`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知接收人快照表';
CREATE TABLE IF NOT EXISTS `notice_recipient_account` (
  `id` bigint NOT NULL COMMENT '主键',
  `user_id` bigint NOT NULL COMMENT '用户 ID',
  `account_type` varchar(32) NOT NULL COMMENT '账户类型',
  `account_value` varchar(255) NOT NULL COMMENT '账户标识',
  `display_name` varchar(128) DEFAULT NULL COMMENT '显示名称',
  `verified_status` varchar(32) NOT NULL DEFAULT 'PENDING_VERIFY' COMMENT '验证状态',
  `default_account` tinyint NOT NULL DEFAULT '0' COMMENT '是否默认',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_recipient_account_value` (`tenant_id`,`user_id`,`account_type`,`account_value`),
  KEY `idx_notice_recipient_account_user` (`tenant_id`,`user_id`,`account_type`,`verified_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知接收账户表';
CREATE TABLE IF NOT EXISTS `notice_retry_log` (
  `id` bigint NOT NULL COMMENT '主键',
  `send_record_id` bigint NOT NULL COMMENT '发送记录 ID',
  `retry_count` int NOT NULL DEFAULT '0' COMMENT '重试次数',
  `retry_type` varchar(32) NOT NULL COMMENT '重试类型',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  PRIMARY KEY (`id`),
  KEY `idx_notice_retry_record` (`send_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知重试日志表';
CREATE TABLE IF NOT EXISTS `notice_send_record` (
  `id` bigint NOT NULL COMMENT '主键',
  `task_id` bigint NOT NULL COMMENT '任务 ID',
  `recipient_id` bigint NOT NULL COMMENT '接收人 ID',
  `biz_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `biz_id` varchar(128) DEFAULT NULL COMMENT '业务对象 ID',
  `business_channel_template_id` bigint DEFAULT NULL COMMENT '业务渠道模板 ID',
  `template_version` int DEFAULT NULL COMMENT '模板版本',
  `channel_type` varchar(32) NOT NULL COMMENT '渠道类型',
  `channel_config_id` bigint DEFAULT NULL COMMENT '渠道配置 ID',
  `request_id` varchar(128) NOT NULL COMMENT '请求流水号',
  `provider_message_id` varchar(128) DEFAULT NULL COMMENT '供应商消息 ID',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '发送状态',
  `rendered_title` varchar(200) DEFAULT NULL COMMENT '渲染后标题',
  `rendered_content` text COMMENT '渲染后内容快照',
  `request_snapshot` text COMMENT '请求摘要 JSON',
  `response_snapshot` text COMMENT '响应摘要 JSON',
  `fail_code` varchar(64) DEFAULT NULL COMMENT '失败码',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `retry_count` int NOT NULL DEFAULT '0' COMMENT '已重试次数',
  `next_retry_time` datetime DEFAULT NULL COMMENT '下次重试时间',
  `sent_at` datetime DEFAULT NULL COMMENT '发送时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_send_request` (`tenant_id`,`request_id`),
  KEY `idx_notice_send_task` (`task_id`),
  KEY `idx_notice_send_status` (`tenant_id`,`status`,`next_retry_time`),
  KEY `idx_notice_send_recipient` (`tenant_id`,`recipient_id`,`channel_type`),
  KEY `idx_notice_send_biz` (`tenant_id`,`biz_type`,`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知发送记录表';
CREATE TABLE IF NOT EXISTS `notice_setting` (
  `id` bigint NOT NULL COMMENT '主键',
  `setting_key` varchar(128) NOT NULL COMMENT '配置键',
  `setting_value` text COMMENT '配置值',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_setting_key` (`tenant_id`,`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知设置表';
CREATE TABLE IF NOT EXISTS `notice_site_message` (
  `id` bigint NOT NULL COMMENT '主键',
  `task_id` bigint DEFAULT NULL COMMENT '来源任务 ID',
  `send_record_id` bigint DEFAULT NULL COMMENT '来源发送记录 ID',
  `user_id` bigint NOT NULL COMMENT '接收用户 ID',
  `title` varchar(200) NOT NULL COMMENT '通知标题',
  `content` text NOT NULL COMMENT '通知内容',
  `message_scene` varchar(64) DEFAULT NULL COMMENT '系统消息场景',
  `subject_type` varchar(64) DEFAULT NULL COMMENT '业务对象类型',
  `subject_id` varchar(128) DEFAULT NULL COMMENT '业务对象 ID',
  `subject_name` varchar(128) DEFAULT NULL COMMENT '业务对象名称快照',
  `target_type` varchar(32) DEFAULT NULL COMMENT '跳转目标类型',
  `target_key` varchar(128) DEFAULT NULL COMMENT '命名目标键',
  `target_params_json` text COMMENT '目标参数 JSON',
  `target_open_mode` varchar(32) DEFAULT NULL COMMENT '跳转打开方式',
  `data_json` text COMMENT '业务数据快照 JSON',
  `expire_time` datetime DEFAULT NULL COMMENT '消息过期时间',
  `priority` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '优先级',
  `read_status` varchar(32) NOT NULL DEFAULT 'UNREAD' COMMENT '已读状态',
  `read_time` datetime DEFAULT NULL COMMENT '阅读时间',
  `delete_status` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '删除状态',
  `revoke_status` tinyint NOT NULL DEFAULT '0' COMMENT '是否撤回',
  `top_status` tinyint NOT NULL DEFAULT '0' COMMENT '是否置顶',
  `biz_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `biz_id` varchar(128) DEFAULT NULL COMMENT '业务对象 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  PRIMARY KEY (`id`),
  KEY `idx_notice_site_user` (`tenant_id`,`user_id`,`delete_status`,`created_at`),
  KEY `idx_notice_site_unread` (`tenant_id`,`user_id`,`read_status`),
  KEY `idx_notice_site_biz` (`tenant_id`,`biz_type`,`biz_id`),
  KEY `idx_notice_site_task` (`task_id`),
  KEY `idx_notice_site_subject` (`tenant_id`,`subject_type`,`subject_id`),
  KEY `idx_notice_site_scene` (`tenant_id`,`message_scene`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='站内信消息表';
CREATE TABLE IF NOT EXISTS `notice_site_message_action` (
  `id` bigint NOT NULL COMMENT '主键',
  `message_id` bigint NOT NULL COMMENT '系统消息 ID',
  `action_code` varchar(64) NOT NULL COMMENT '动作编码',
  `action_label` varchar(64) NOT NULL COMMENT '动作展示名称',
  `interaction_type` varchar(32) NOT NULL DEFAULT 'EVENT' COMMENT '交互类型：EVENT、ROUTE',
  `event_type` varchar(128) DEFAULT NULL COMMENT '投递事件类型',
  `target_type` varchar(32) DEFAULT NULL COMMENT '动作跳转目标类型',
  `target_key` varchar(128) DEFAULT NULL COMMENT '动作命名目标键',
  `target_params_json` text COMMENT '动作目标参数 JSON',
  `target_open_mode` varchar(32) DEFAULT NULL COMMENT '动作跳转打开方式',
  `confirm_required` tinyint NOT NULL DEFAULT '0' COMMENT '是否需要确认',
  `input_schema` text COMMENT '输入 JSON Schema',
  `status` varchar(32) NOT NULL DEFAULT 'AVAILABLE' COMMENT '动作状态',
  `failure_reason` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序',
  `expire_time` datetime DEFAULT NULL COMMENT '动作过期时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_site_action_code` (`tenant_id`,`message_id`,`action_code`),
  KEY `idx_notice_site_action_message` (`tenant_id`,`message_id`,`status`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统消息动作表';
CREATE TABLE IF NOT EXISTS `notice_site_message_action_request` (
  `id` bigint NOT NULL COMMENT '主键',
  `message_id` bigint NOT NULL COMMENT '系统消息 ID',
  `action_id` bigint NOT NULL COMMENT '系统消息动作 ID',
  `action_code` varchar(64) NOT NULL COMMENT '动作编码',
  `actor_user_id` bigint NOT NULL COMMENT '操作用户 ID',
  `request_id` varchar(160) NOT NULL COMMENT '动作请求 ID',
  `input_json` text COMMENT '动作输入 JSON',
  `status` varchar(32) NOT NULL DEFAULT 'REQUESTED' COMMENT '请求状态',
  `fail_code` varchar(64) DEFAULT NULL COMMENT '失败码',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `result_json` text COMMENT '业务处理结果 JSON',
  `event_id` varchar(64) DEFAULT NULL COMMENT '领域事件 ID',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `finished_at` datetime DEFAULT NULL COMMENT '完成时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_site_action_request` (`tenant_id`,`request_id`),
  KEY `idx_notice_site_action_request_message` (`tenant_id`,`message_id`,`action_code`,`actor_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统消息动作请求流水表';
CREATE TABLE IF NOT EXISTS `notice_task` (
  `id` bigint NOT NULL COMMENT '主键',
  `task_code` varchar(64) NOT NULL COMMENT '任务编码',
  `biz_type` varchar(64) NOT NULL COMMENT '业务类型',
  `biz_id` varchar(128) DEFAULT NULL COMMENT '业务对象 ID',
  `idempotent_key` varchar(128) DEFAULT NULL COMMENT '幂等键',
  `params_snapshot` text COMMENT '业务参数快照 JSON',
  `recipient_targets_snapshot` text COMMENT '接收目标快照 JSON',
  `channel_types` varchar(255) DEFAULT NULL COMMENT '实际渠道集合快照',
  `message_scene` varchar(64) DEFAULT NULL COMMENT '系统消息场景',
  `message_subject_type` varchar(64) DEFAULT NULL COMMENT '系统消息业务对象类型',
  `message_subject_id` varchar(128) DEFAULT NULL COMMENT '系统消息业务对象 ID',
  `message_subject_name` varchar(128) DEFAULT NULL COMMENT '系统消息业务对象名称快照',
  `message_target_type` varchar(32) DEFAULT NULL COMMENT '系统消息跳转目标类型',
  `message_target_key` varchar(128) DEFAULT NULL COMMENT '系统消息命名目标键',
  `message_target_params_json` text COMMENT '系统消息目标参数 JSON',
  `message_target_open_mode` varchar(32) DEFAULT NULL COMMENT '系统消息跳转打开方式',
  `message_data_json` text COMMENT '系统消息业务数据快照 JSON',
  `message_actions_json` text COMMENT '系统消息动作快照 JSON',
  `message_expire_time` datetime DEFAULT NULL COMMENT '系统消息过期时间',
  `send_mode` varchar(32) NOT NULL DEFAULT 'IMMEDIATE' COMMENT '发送模式',
  `scheduled_time` datetime DEFAULT NULL COMMENT '定时发送时间',
  `status` varchar(32) NOT NULL DEFAULT 'WAITING' COMMENT '任务状态',
  `total_count` int NOT NULL DEFAULT '0' COMMENT '总发送数',
  `success_count` int NOT NULL DEFAULT '0' COMMENT '成功数',
  `fail_count` int NOT NULL DEFAULT '0' COMMENT '失败数',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_task_code` (`task_code`),
  UNIQUE KEY `uk_notice_task_idempotent` (`tenant_id`,`idempotent_key`),
  KEY `idx_notice_task_biz` (`tenant_id`,`biz_type`,`biz_id`),
  KEY `idx_notice_task_status` (`tenant_id`,`status`,`scheduled_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知任务表';
CREATE TABLE IF NOT EXISTS `notice_wecom_sync_mapping` (
  `id` bigint NOT NULL COMMENT '主键',
  `sync_type` varchar(32) NOT NULL COMMENT '同步对象类型：DEPARTMENT/USER',
  `external_id` varchar(128) NOT NULL COMMENT '企业微信外部ID',
  `local_id` bigint NOT NULL COMMENT 'Mango本地ID',
  `data_hash` varchar(64) DEFAULT NULL COMMENT '同步数据指纹',
  `display_name` varchar(128) DEFAULT NULL COMMENT '显示名称快照',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_wecom_sync_external` (`tenant_id`,`sync_type`,`external_id`),
  KEY `idx_notice_wecom_sync_local` (`tenant_id`,`sync_type`,`local_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='企业微信同步映射表';
