CREATE TABLE IF NOT EXISTS `notice_inbound_message` (
  `id` bigint NOT NULL COMMENT '主键',
  `channel_config_id` bigint NOT NULL COMMENT '接收渠道配置 ID',
  `channel_type` varchar(32) NOT NULL COMMENT '渠道类型',
  `provider_code` varchar(64) DEFAULT NULL COMMENT '来源提供方',
  `source_key` varchar(255) NOT NULL COMMENT '稳定来源幂等键',
  `message_id` varchar(255) DEFAULT NULL COMMENT '来源消息 ID',
  `subject` varchar(500) DEFAULT NULL COMMENT '主题',
  `from_address` varchar(500) DEFAULT NULL COMMENT '发件人',
  `to_addresses_json` text COMMENT '收件人 JSON',
  `body_text` mediumtext COMMENT '纯文本正文',
  `body_html` mediumtext COMMENT 'HTML 正文',
  `raw_headers_json` text COMMENT '非敏感原始头 JSON',
  `status` varchar(32) NOT NULL COMMENT '入站状态',
  `event_id` varchar(64) NOT NULL COMMENT '稳定广播事件 ID',
  `failure_code` varchar(128) DEFAULT NULL COMMENT '失败码',
  `failure_reason` varchar(1000) DEFAULT NULL COMMENT '失败摘要',
  `attempt_count` int NOT NULL DEFAULT 0 COMMENT '处理尝试次数',
  `next_retry_at` datetime DEFAULT NULL COMMENT '下次内部重试时间',
  `received_at` datetime NOT NULL COMMENT '接收时间',
  `processed_at` datetime DEFAULT NULL COMMENT '处理时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_inbound_message_source` (`tenant_id`,`channel_config_id`,`source_key`),
  UNIQUE KEY `uk_notice_inbound_message_event` (`tenant_id`,`event_id`),
  KEY `idx_notice_inbound_message_status` (`tenant_id`,`status`,`received_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知入站消息表';

CREATE TABLE IF NOT EXISTS `notice_inbound_attachment` (
  `id` bigint NOT NULL COMMENT '主键',
  `message_id` bigint NOT NULL COMMENT '入站消息 ID',
  `attachment_index` int NOT NULL COMMENT '附件序号',
  `file_id` bigint DEFAULT NULL COMMENT 'mango-file 文件 ID',
  `file_name` varchar(255) NOT NULL COMMENT '文件名',
  `content_type` varchar(128) DEFAULT NULL COMMENT '内容类型',
  `file_size` bigint NOT NULL COMMENT '文件大小',
  `content_sha256` varchar(64) DEFAULT NULL COMMENT '内容摘要',
  `status` varchar(32) NOT NULL COMMENT '附件状态',
  `failure_code` varchar(128) DEFAULT NULL COMMENT '失败码',
  `failure_reason` varchar(1000) DEFAULT NULL COMMENT '失败摘要',
  `attempt_count` int NOT NULL DEFAULT 0 COMMENT '附件处理尝试次数',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_inbound_attachment_index` (`tenant_id`,`message_id`,`attachment_index`),
  KEY `idx_notice_inbound_attachment_file` (`tenant_id`,`file_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知入站附件表';

CREATE TABLE IF NOT EXISTS `notice_inbound_receive_cursor` (
  `id` bigint NOT NULL COMMENT '主键',
  `channel_config_id` bigint NOT NULL COMMENT '渠道配置 ID',
  `protocol` varchar(16) NOT NULL COMMENT '邮箱协议',
  `cursor_value` varchar(500) DEFAULT NULL COMMENT '协议游标',
  `cursor_version` varchar(255) DEFAULT NULL COMMENT '协议游标版本',
  `last_polled_at` datetime DEFAULT NULL COMMENT '最近轮询时间',
  `next_poll_at` datetime DEFAULT NULL COMMENT '下次轮询时间',
  `last_failure_code` varchar(128) DEFAULT NULL COMMENT '最近失败码',
  `last_failure_reason` varchar(1000) DEFAULT NULL COMMENT '最近失败摘要',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_inbound_cursor_config` (`tenant_id`,`channel_config_id`),
  KEY `idx_notice_inbound_cursor_poll` (`tenant_id`,`next_poll_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通知入站邮箱游标表';
