CREATE TABLE IF NOT EXISTS cms_site (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    site_name VARCHAR(128) NOT NULL,
    site_code VARCHAR(64) NOT NULL,
    logo_file_id VARCHAR(128) NULL,
    description VARCHAR(512) NULL,
    domain VARCHAR(255) NULL,
    status VARCHAR(32) NOT NULL,
    default_language VARCHAR(32) NULL,
    seo_title VARCHAR(255) NULL,
    seo_keywords VARCHAR(512) NULL,
    seo_description VARCHAR(1024) NULL,
    footer_copyright VARCHAR(512) NULL,
    icp_record VARCHAR(255) NULL,
    contact_info VARCHAR(1024) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uk_cms_site_code (tenant_id, site_code, deleted),
    UNIQUE KEY uk_cms_site_domain (domain, deleted)
);

CREATE TABLE IF NOT EXISTS cms_site_category (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    site_id BIGINT NOT NULL,
    parent_id BIGINT NOT NULL DEFAULT 0,
    category_name VARCHAR(128) NOT NULL,
    category_code VARCHAR(64) NOT NULL,
    category_type VARCHAR(32) NOT NULL,
    access_path VARCHAR(255) NULL,
    external_url VARCHAR(512) NULL,
    sort INT NOT NULL DEFAULT 0,
    visible_status VARCHAR(32) NOT NULL,
    access_type VARCHAR(32) NOT NULL,
    role_codes VARCHAR(512) NULL,
    seo_title VARCHAR(255) NULL,
    seo_keywords VARCHAR(512) NULL,
    seo_description VARCHAR(1024) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uk_cms_site_category_code (tenant_id, site_id, category_code, deleted),
    KEY idx_cms_site_category_parent (tenant_id, site_id, parent_id, deleted)
);

CREATE TABLE IF NOT EXISTS cms_content_category (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    parent_id BIGINT NOT NULL DEFAULT 0,
    category_code VARCHAR(64) NOT NULL,
    category_name VARCHAR(128) NOT NULL,
    sort INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    remark VARCHAR(512) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uk_cms_content_category_code (tenant_id, category_code, deleted)
);

CREATE TABLE IF NOT EXISTS cms_content_tag (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    tag_code VARCHAR(64) NOT NULL,
    tag_name VARCHAR(128) NOT NULL,
    sort INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    remark VARCHAR(512) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uk_cms_content_tag_code (tenant_id, tag_code, deleted)
);

CREATE TABLE IF NOT EXISTS cms_content (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255) NULL,
    summary VARCHAR(1024) NULL,
    content_type VARCHAR(32) NOT NULL,
    cover_file_id VARCHAR(128) NULL,
    body LONGTEXT NULL,
    external_url VARCHAR(512) NULL,
    attachment_file_id VARCHAR(128) NULL,
    video_file_id VARCHAR(128) NULL,
    source VARCHAR(128) NULL,
    author VARCHAR(128) NULL,
    category_id BIGINT NULL,
    seo_title VARCHAR(255) NULL,
    seo_keywords VARCHAR(512) NULL,
    seo_description VARCHAR(1024) NULL,
    status VARCHAR(32) NOT NULL,
    publish_time DATETIME NULL,
    offline_time DATETIME NULL,
    review_comment VARCHAR(1024) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    KEY idx_cms_content_status (tenant_id, status, deleted),
    KEY idx_cms_content_category (tenant_id, category_id, deleted)
);

CREATE TABLE IF NOT EXISTS cms_content_tag_rel (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    content_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uk_cms_content_tag_rel (tenant_id, content_id, tag_id, deleted)
);

CREATE TABLE IF NOT EXISTS cms_content_publish (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    content_id BIGINT NOT NULL,
    site_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    publish_status VARCHAR(32) NOT NULL,
    publish_time DATETIME NULL,
    scheduled_publish_time DATETIME NULL,
    offline_time DATETIME NULL,
    top TINYINT NOT NULL DEFAULT 0,
    top_scope VARCHAR(32) NULL,
    recommended TINYINT NOT NULL DEFAULT 0,
    recommendation_type VARCHAR(32) NULL,
    sort INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uk_cms_publish_position (tenant_id, content_id, site_id, category_id, deleted),
    KEY idx_cms_publish_site (tenant_id, site_id, category_id, publish_status, deleted)
);

CREATE TABLE IF NOT EXISTS cms_navigation (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    site_id BIGINT NOT NULL,
    nav_type VARCHAR(32) NOT NULL,
    nav_name VARCHAR(128) NOT NULL,
    jump_type VARCHAR(32) NOT NULL,
    category_id BIGINT NULL,
    content_id BIGINT NULL,
    external_url VARCHAR(512) NULL,
    open_target VARCHAR(32) NULL,
    sort INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    KEY idx_cms_navigation_site (tenant_id, site_id, nav_type, status, deleted)
);

CREATE TABLE IF NOT EXISTS cms_banner (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    site_id BIGINT NOT NULL,
    position VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255) NULL,
    media_type VARCHAR(32) NOT NULL,
    media_file_id VARCHAR(128) NULL,
    jump_url VARCHAR(512) NULL,
    start_time DATETIME NULL,
    end_time DATETIME NULL,
    sort INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    KEY idx_cms_banner_site (tenant_id, site_id, position, status, deleted)
);

CREATE TABLE IF NOT EXISTS cms_advertisement (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    site_id BIGINT NOT NULL,
    ad_code VARCHAR(64) NOT NULL,
    ad_name VARCHAR(128) NOT NULL,
    position VARCHAR(64) NOT NULL,
    ad_type VARCHAR(32) NOT NULL,
    material_file_id VARCHAR(128) NULL,
    jump_url VARCHAR(512) NULL,
    start_time DATETIME NULL,
    end_time DATETIME NULL,
    sort INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uk_cms_ad_code (tenant_id, site_id, ad_code, deleted),
    KEY idx_cms_ad_site (tenant_id, site_id, position, status, deleted)
);

CREATE TABLE IF NOT EXISTS cms_site_setting (
    id BIGINT PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    org_id BIGINT NULL,
    site_id BIGINT NOT NULL,
    seo_title VARCHAR(255) NULL,
    seo_keywords VARCHAR(512) NULL,
    seo_description VARCHAR(1024) NULL,
    footer_copyright VARCHAR(512) NULL,
    icp_record VARCHAR(255) NULL,
    contact_info VARCHAR(1024) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NULL,
    updated_by BIGINT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uk_cms_site_setting (tenant_id, site_id, deleted)
);
