-- Baseline migration for module: mango-job

CREATE TABLE IF NOT EXISTS `mango_job_definition` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` varchar(64) NOT NULL COMMENT '租户ID',
  `app_code` varchar(128) NOT NULL COMMENT '所属逻辑应用',
  `job_code` varchar(128) NOT NULL COMMENT '任务编码',
  `job_name` varchar(128) NOT NULL COMMENT '任务名称',
  `job_type` varchar(32) NOT NULL COMMENT '任务类型',
  `schedule_type` varchar(32) NOT NULL COMMENT '调度类型',
  `schedule_expression` varchar(256) DEFAULT NULL COMMENT '调度表达式',
  `handler_name` varchar(256) DEFAULT NULL COMMENT '处理器名称',
  `param_schema` text DEFAULT NULL COMMENT '参数表单 schema',
  `param_value` text DEFAULT NULL COMMENT '默认参数 JSON',
  `misfire_strategy` varchar(64) DEFAULT NULL COMMENT '错过触发策略',
  `concurrency_policy` varchar(64) DEFAULT NULL COMMENT '并发策略',
  `timeout_seconds` int DEFAULT NULL COMMENT '执行超时秒数',
  `retry_policy` text DEFAULT NULL COMMENT '重试策略 JSON',
  `status` varchar(32) NOT NULL COMMENT '任务状态',
  `engine_type` varchar(32) NOT NULL COMMENT '引擎类型',
  `engine_app_id` varchar(128) DEFAULT NULL COMMENT '引擎应用标识',
  `engine_job_id` varchar(128) DEFAULT NULL COMMENT '引擎任务标识',
  `sync_status` varchar(32) NOT NULL COMMENT '引擎同步状态',
  `sync_error` varchar(1024) DEFAULT NULL COMMENT '同步错误摘要',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_job_tenant_app_code` (`tenant_id`, `app_code`, `job_code`),
  KEY `idx_job_status` (`tenant_id`, `status`, `updated_at`),
  KEY `idx_job_engine` (`engine_type`, `engine_app_id`, `engine_job_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Mango Job 任务定义';

CREATE TABLE IF NOT EXISTS `mango_job_instance` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` varchar(64) NOT NULL COMMENT '租户ID',
  `job_id` bigint NOT NULL COMMENT 'Mango 任务 ID',
  `trigger_type` varchar(32) NOT NULL COMMENT '触发来源',
  `trigger_user_id` bigint DEFAULT NULL COMMENT '触发人 ID',
  `trigger_time` datetime NOT NULL COMMENT '触发时间',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `status` varchar(32) NOT NULL COMMENT '实例状态',
  `duration_millis` bigint DEFAULT NULL COMMENT '执行耗时毫秒',
  `engine_type` varchar(32) NOT NULL COMMENT '引擎类型',
  `engine_instance_id` varchar(128) DEFAULT NULL COMMENT '引擎实例标识',
  `error_summary` varchar(1024) DEFAULT NULL COMMENT '错误摘要',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '链路追踪 ID',
  `trigger_batch_no` varchar(128) DEFAULT NULL COMMENT '触发批次号',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_instance_job_time` (`tenant_id`, `job_id`, `trigger_time`),
  KEY `idx_instance_status_time` (`tenant_id`, `status`, `trigger_time`),
  KEY `idx_instance_engine` (`engine_type`, `engine_instance_id`),
  KEY `idx_instance_batch` (`tenant_id`, `trigger_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Mango Job 执行实例摘要';

CREATE TABLE IF NOT EXISTS `mango_job_log_index` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` varchar(64) NOT NULL COMMENT '租户ID',
  `job_id` bigint NOT NULL COMMENT 'Mango 任务 ID',
  `instance_id` bigint NOT NULL COMMENT 'Mango 实例 ID',
  `engine_type` varchar(32) NOT NULL COMMENT '引擎类型',
  `engine_instance_id` varchar(128) DEFAULT NULL COMMENT '引擎实例标识',
  `log_location` varchar(512) DEFAULT NULL COMMENT '日志位置或拉取游标',
  `read_offset` bigint DEFAULT NULL COMMENT '读取偏移量',
  `error_summary` varchar(1024) DEFAULT NULL COMMENT '错误摘要',
  `last_fetched_at` datetime DEFAULT NULL COMMENT '最近拉取时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_log_instance` (`tenant_id`, `instance_id`),
  KEY `idx_log_job_time` (`tenant_id`, `job_id`, `created_at`),
  KEY `idx_log_engine` (`engine_type`, `engine_instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Mango Job 执行日志索引';

CREATE TABLE IF NOT EXISTS `mango_job_worker_snapshot` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` varchar(64) NOT NULL COMMENT '租户ID',
  `app_code` varchar(128) NOT NULL COMMENT '所属逻辑应用',
  `worker_address` varchar(256) NOT NULL COMMENT 'Worker 地址',
  `engine_type` varchar(32) NOT NULL COMMENT '引擎类型',
  `engine_worker_id` varchar(128) DEFAULT NULL COMMENT '引擎 Worker 标识',
  `last_heartbeat_at` datetime DEFAULT NULL COMMENT '最近心跳时间',
  `status` varchar(32) NOT NULL COMMENT 'Worker 状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_worker_engine_address` (`engine_type`, `worker_address`),
  KEY `idx_worker_app_status` (`tenant_id`, `app_code`, `status`),
  KEY `idx_worker_heartbeat` (`last_heartbeat_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Mango Job Worker 快照';

CREATE TABLE IF NOT EXISTS `mango_job_alarm_rule` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` varchar(64) NOT NULL COMMENT '租户ID',
  `job_id` bigint DEFAULT NULL COMMENT 'Mango 任务 ID',
  `app_code` varchar(128) NOT NULL COMMENT '所属逻辑应用',
  `rule_name` varchar(128) NOT NULL COMMENT '告警规则名称',
  `alarm_type` varchar(64) NOT NULL COMMENT '告警类型',
  `trigger_condition` text NOT NULL COMMENT '触发条件 JSON',
  `notice_scene_code` varchar(128) NOT NULL COMMENT '通知场景编码',
  `notice_template_code` varchar(128) NOT NULL COMMENT '通知模板编码',
  `notice_params` text DEFAULT NULL COMMENT '通知参数 JSON',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_alarm_job` (`tenant_id`, `job_id`, `enabled`),
  KEY `idx_alarm_app` (`tenant_id`, `app_code`, `enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Mango Job 告警规则';

CREATE TABLE IF NOT EXISTS `mango_job_engine_mapping` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` varchar(64) NOT NULL COMMENT '租户ID',
  `job_id` bigint DEFAULT NULL COMMENT 'Mango 任务 ID',
  `instance_id` bigint DEFAULT NULL COMMENT 'Mango 实例 ID',
  `app_code` varchar(128) NOT NULL COMMENT '所属逻辑应用',
  `engine_type` varchar(32) NOT NULL COMMENT '引擎类型',
  `engine_app_id` varchar(128) DEFAULT NULL COMMENT '引擎应用标识',
  `engine_job_id` varchar(128) DEFAULT NULL COMMENT '引擎任务标识',
  `engine_instance_id` varchar(128) DEFAULT NULL COMMENT '引擎实例标识',
  `sync_status` varchar(32) NOT NULL COMMENT '同步状态',
  `sync_error` varchar(1024) DEFAULT NULL COMMENT '同步错误摘要',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_mapping_job` (`tenant_id`, `job_id`),
  KEY `idx_mapping_instance` (`tenant_id`, `instance_id`),
  KEY `idx_mapping_engine_job` (`engine_type`, `engine_app_id`, `engine_job_id`),
  KEY `idx_mapping_engine_instance` (`engine_type`, `engine_instance_id`),
  KEY `idx_mapping_sync_status` (`tenant_id`, `sync_status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Mango Job 引擎映射';

CREATE TABLE IF NOT EXISTS `mango_job_operation_log` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` varchar(64) NOT NULL COMMENT '租户ID',
  `job_id` bigint DEFAULT NULL COMMENT 'Mango 任务 ID',
  `instance_id` bigint DEFAULT NULL COMMENT 'Mango 实例 ID',
  `operation_type` varchar(64) NOT NULL COMMENT '操作类型',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人 ID',
  `operator_name` varchar(128) DEFAULT NULL COMMENT '操作人名称',
  `request_summary` varchar(2048) DEFAULT NULL COMMENT '脱敏请求摘要',
  `result_status` varchar(32) NOT NULL COMMENT '操作结果',
  `error_summary` varchar(1024) DEFAULT NULL COMMENT '错误摘要',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '链路追踪 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_operation_job_time` (`tenant_id`, `job_id`, `created_at`),
  KEY `idx_operation_instance` (`tenant_id`, `instance_id`),
  KEY `idx_operation_type_time` (`tenant_id`, `operation_type`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Mango Job 操作日志';
