-- Seed disabled payment channel bill fetch job definition.

INSERT INTO `mango_job_definition` (
  `id`,
  `tenant_id`,
  `app_code`,
  `owner_service`,
  `worker_group`,
  `module_code`,
  `job_code`,
  `job_name`,
  `job_type`,
  `schedule_type`,
  `schedule_expression`,
  `handler_name`,
  `handler_version`,
  `param_schema`,
  `param_value`,
  `misfire_strategy`,
  `concurrency_policy`,
  `timeout_seconds`,
  `retry_policy`,
  `timezone`,
  `max_retry_count`,
  `version`,
  `deleted`,
  `status`,
  `engine_type`,
  `engine_app_id`,
  `engine_job_id`,
  `sync_status`,
  `sync_error`,
  `created_by`,
  `created_at`,
  `updated_by`,
  `updated_at`
) VALUES (
  2951200000000000001,
  '1',
  'mango-monolith-app',
  'mango-monolith-app',
  'mango-monolith-app',
  'mango-payment',
  'payment_channel_bill_fetch_yesterday',
  '支付通道昨日账单拉取',
  'BUILTIN',
  'CRON',
  '0 10 0 * * ?',
  'paymentChannelBillFetchJobHandler',
  NULL,
  '{"type":"object","properties":{"billDate":{"type":"string","title":"账单日期","description":"yyyy-MM-dd；为空时默认拉取昨天账单"}}}',
  '{}',
  'FIRE_ONCE',
  'SERIAL',
  1800,
  '{"maxRetryTimes":1}',
  'Asia/Shanghai',
  1,
  0,
  0,
  'DISABLED',
  'MANGO_NATIVE',
  NULL,
  NULL,
  'PENDING',
  NULL,
  0,
  NOW(),
  0,
  NOW()
)
ON DUPLICATE KEY UPDATE
  `job_name` = VALUES(`job_name`),
  `owner_service` = VALUES(`owner_service`),
  `worker_group` = VALUES(`worker_group`),
  `module_code` = VALUES(`module_code`),
  `schedule_type` = VALUES(`schedule_type`),
  `schedule_expression` = VALUES(`schedule_expression`),
  `handler_name` = VALUES(`handler_name`),
  `param_schema` = VALUES(`param_schema`),
  `param_value` = VALUES(`param_value`),
  `misfire_strategy` = VALUES(`misfire_strategy`),
  `concurrency_policy` = VALUES(`concurrency_policy`),
  `timeout_seconds` = VALUES(`timeout_seconds`),
  `retry_policy` = VALUES(`retry_policy`),
  `timezone` = VALUES(`timezone`),
  `max_retry_count` = VALUES(`max_retry_count`),
  `deleted` = 0,
  `status` = CASE
    WHEN `mango_job_definition`.`status` = 'DRAFT' THEN 'DISABLED'
    ELSE `mango_job_definition`.`status`
  END,
  `sync_status` = CASE
    WHEN `mango_job_definition`.`engine_job_id` IS NULL OR `mango_job_definition`.`engine_job_id` = '' THEN 'PENDING'
    ELSE `mango_job_definition`.`sync_status`
  END,
  `updated_by` = VALUES(`updated_by`),
  `updated_at` = NOW();
