-- Mango System baseline schema.
-- Flyway owns DDL only. Required and demo data are registered under META-INF/mango.

CREATE TABLE IF NOT EXISTS `sys_dict_type` (
  `id` bigint NOT NULL COMMENT '主键',
  `dict_type` varchar(50) NOT NULL COMMENT '字典类型',
  `dict_name` varchar(100) NOT NULL COMMENT '字典名称',
  `domain_code` varchar(64) NOT NULL DEFAULT 'COMMON' COMMENT '业务域编码',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0-禁用 1-启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_dict_type_tenant_type` (`tenant_id`, `dict_type`),
  KEY `idx_sys_dict_type_domain` (`tenant_id`, `domain_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典类型表';

CREATE TABLE IF NOT EXISTS `sys_dict_data` (
  `id` bigint NOT NULL COMMENT '主键',
  `dict_type` varchar(50) NOT NULL COMMENT '字典类型',
  `dict_label` varchar(100) NOT NULL COMMENT '字典标签',
  `dict_value` varchar(100) NOT NULL COMMENT '字典值',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0-禁用 1-启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_sys_dict_data_type` (`tenant_id`, `dict_type`),
  KEY `idx_sys_dict_data_value` (`tenant_id`, `dict_type`, `dict_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典数据表';

CREATE TABLE IF NOT EXISTS `sys_config` (
  `id` bigint NOT NULL COMMENT '主键',
  `config_key` varchar(100) NOT NULL COMMENT '配置键',
  `config_value` text NOT NULL COMMENT '配置值',
  `config_name` varchar(100) NOT NULL COMMENT '配置名称',
  `type` varchar(20) NOT NULL COMMENT '类型：SYSTEM/BUSINESS/SECURITY/FEATURE',
  `domain_code` varchar(64) NOT NULL DEFAULT 'COMMON' COMMENT '业务域编码',
  `value_type` varchar(32) DEFAULT 'STRING' COMMENT '配置值展示与编辑类型',
  `group_code` varchar(64) DEFAULT NULL COMMENT '配置分组编码',
  `group_name` varchar(100) DEFAULT NULL COMMENT '配置分组名称',
  `default_value` text DEFAULT NULL COMMENT '默认值',
  `options` text DEFAULT NULL COMMENT '选项列表 JSON',
  `option_source` varchar(32) NOT NULL DEFAULT 'CUSTOM' COMMENT '选项来源：CUSTOM/DICT',
  `dict_type` varchar(50) DEFAULT NULL COMMENT '绑定字典类型',
  `editable` tinyint NOT NULL DEFAULT '1' COMMENT '是否可编辑：0-否 1-是',
  `editable_reason` varchar(200) DEFAULT NULL COMMENT '不可编辑原因',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0-禁用 1-启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_config_tenant_key` (`tenant_id`, `config_key`),
  KEY `idx_sys_config_type` (`tenant_id`, `type`),
  KEY `idx_sys_config_domain` (`tenant_id`, `domain_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统配置表';

CREATE TABLE IF NOT EXISTS `sys_login_log` (
  `id` bigint NOT NULL COMMENT '主键',
  `user_id` bigint DEFAULT NULL COMMENT '用户 ID',
  `username` varchar(64) DEFAULT NULL COMMENT '用户名',
  `login_type` varchar(20) DEFAULT NULL COMMENT '登录类型',
  `ip` varchar(128) DEFAULT NULL COMMENT '登录 IP',
  `location` varchar(255) DEFAULT NULL COMMENT '登录地点',
  `browser` varchar(128) DEFAULT NULL COMMENT '浏览器',
  `os` varchar(64) DEFAULT NULL COMMENT '操作系统',
  `status` tinyint DEFAULT NULL COMMENT '登录状态',
  `msg` varchar(500) DEFAULT NULL COMMENT '提示消息',
  `login_time` datetime DEFAULT NULL COMMENT '登录时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_sys_login_log_user_id` (`tenant_id`, `user_id`),
  KEY `idx_sys_login_log_login_time` (`tenant_id`, `login_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='登录日志表';

CREATE TABLE IF NOT EXISTS `sys_operation_log` (
  `id` bigint NOT NULL COMMENT '主键',
  `user_id` bigint DEFAULT NULL COMMENT '用户 ID',
  `username` varchar(64) DEFAULT NULL COMMENT '用户名',
  `module` varchar(64) DEFAULT NULL COMMENT '操作模块',
  `operation` varchar(100) DEFAULT NULL COMMENT '操作名称',
  `method` varchar(200) DEFAULT NULL COMMENT '请求方法',
  `handler_method` varchar(200) DEFAULT NULL COMMENT '处理器方法',
  `url` varchar(500) DEFAULT NULL COMMENT '请求路径',
  `params` text COMMENT '请求参数',
  `result` text COMMENT '请求结果',
  `status` tinyint DEFAULT NULL COMMENT '操作状态',
  `error_msg` varchar(500) DEFAULT NULL COMMENT '错误消息',
  `duration` bigint DEFAULT NULL COMMENT '执行时间（毫秒）',
  `ip` varchar(128) DEFAULT NULL COMMENT '操作 IP',
  `location` varchar(255) DEFAULT NULL COMMENT 'IP 归属地',
  `operate_time` datetime DEFAULT NULL COMMENT '操作时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_sys_operation_log_user_id` (`tenant_id`, `user_id`),
  KEY `idx_sys_operation_log_operate_time` (`tenant_id`, `operate_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志表';

CREATE TABLE IF NOT EXISTS `sys_tenant` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_name` varchar(100) NOT NULL COMMENT '租户名称',
  `tenant_code` varchar(50) NOT NULL COMMENT '租户编码',
  `institution_type` varchar(32) NOT NULL DEFAULT 'ENTERPRISE' COMMENT '机构类型',
  `capability_codes` varchar(500) DEFAULT NULL COMMENT '开通能力编码',
  `package_id` bigint DEFAULT NULL COMMENT '菜单授权套餐 ID',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '机构生命周期状态：0-禁用 1-启用 2-冻结 9-归档',
  `contact` varchar(64) DEFAULT NULL COMMENT '联系人',
  `mobile` varchar(20) DEFAULT NULL COMMENT '手机号',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '数据所属租户',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_tenant_code` (`tenant_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='租户表';

CREATE TABLE IF NOT EXISTS `sys_area` (
  `id` bigint NOT NULL COMMENT '主键',
  `pid` bigint NOT NULL DEFAULT '0' COMMENT '父级 ID，0 表示根节点',
  `name` varchar(100) NOT NULL COMMENT '地区名称',
  `letter` varchar(32) DEFAULT NULL COMMENT '地区字母',
  `adcode` bigint DEFAULT NULL COMMENT '行政区划编码',
  `location` varchar(100) DEFAULT NULL COMMENT '经纬度',
  `area_sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `area_status` varchar(8) NOT NULL DEFAULT '1' COMMENT '状态：0-未生效 1-生效',
  `area_type` varchar(8) NOT NULL COMMENT '地区类型',
  `hot` varchar(8) NOT NULL DEFAULT '0' COMMENT '是否热门：0-否 1-是',
  `city_code` varchar(32) DEFAULT NULL COMMENT '城市编码',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_sys_area_pid_status` (`tenant_id`, `pid`, `area_status`),
  KEY `idx_sys_area_adcode` (`tenant_id`, `adcode`),
  KEY `idx_sys_area_type` (`tenant_id`, `area_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='行政区划表';

CREATE TABLE IF NOT EXISTS `sys_i18n` (
  `id` bigint NOT NULL COMMENT '主键',
  `name` varchar(100) NOT NULL COMMENT '国际化键名',
  `zh_cn` varchar(500) NOT NULL COMMENT '简体中文',
  `en` varchar(500) NOT NULL COMMENT '英文',
  `description` varchar(500) DEFAULT NULL COMMENT '说明',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_i18n_tenant_name` (`tenant_id`, `name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='国际化表';

CREATE TABLE IF NOT EXISTS `sys_personal_config` (
  `id` bigint NOT NULL COMMENT '主键',
  `user_id` bigint NOT NULL COMMENT '用户 ID',
  `group_code` varchar(64) NOT NULL COMMENT '配置分组',
  `biz_type` varchar(64) NOT NULL COMMENT '业务类型',
  `config_key` varchar(100) NOT NULL COMMENT '配置键',
  `config_value` text NOT NULL COMMENT '配置值',
  `value_type` varchar(20) NOT NULL DEFAULT 'JSON' COMMENT '值类型：JSON/STRING/NUMBER/BOOLEAN',
  `config_name` varchar(100) DEFAULT NULL COMMENT '配置名称',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织 ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_personal_config_scope` (`tenant_id`, `user_id`, `group_code`, `biz_type`, `config_key`),
  KEY `idx_sys_personal_config_user_group` (`tenant_id`, `user_id`, `group_code`, `biz_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='个人参数配置表';
