CREATE TABLE IF NOT EXISTS `sys_route_conf` (
    `id`          BIGINT(20) NOT NULL COMMENT '主键' PRIMARY KEY,
    `route_name`  VARCHAR(100) NOT NULL COMMENT '路由名称',
    `route_type`  TINYINT NOT NULL DEFAULT 1 COMMENT '路由类型: 1-内部 2-外部',
    `route_path`  VARCHAR(255) NOT NULL COMMENT '路由路径',
    `route_desc`  VARCHAR(500) DEFAULT NULL COMMENT '路由描述',
    `sort`        INT NOT NULL DEFAULT 0 COMMENT '排序号',
    `status`      TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0-禁用 1-启用',
    `create_by`   VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `update_by`   VARCHAR(64) DEFAULT NULL COMMENT '修改人',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `created_by` BIGINT DEFAULT NULL COMMENT '创建人 ID',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `tenant_id` VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
    KEY `idx_sys_route_conf_type` (`route_type`),
    KEY `idx_sys_route_conf_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='动态路由配置表';
