ALTER TABLE `sys_area`
  ADD COLUMN `created_by` BIGINT DEFAULT NULL COMMENT '创建人 ID',
  ADD COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ADD COLUMN `updated_by` BIGINT DEFAULT NULL COMMENT '更新人 ID',
  ADD COLUMN `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
