server:
  port: ${MANGO_WORKFLOW_APP_PORT:18621}

spring:
  application:
    name: mango-workflow-capability-app

mango:
  module:
    module-service:
      modules:
        mango-domain:
          service-name: mango-domain-capability-app
        mango-resource:
          service-name: mango-resource-capability-app
  workflow:
    samples:
      enabled: false
