CREATE TABLE IF NOT EXISTS `ai_invocation_audit` (
  `id` bigint NOT NULL,
  `request_id` varchar(64) NOT NULL,
  `user_id` bigint NOT NULL,
  `trace_id` varchar(128) DEFAULT NULL,
  `service_code` varchar(64) NOT NULL,
  `service_type` varchar(32) NOT NULL,
  `capability` varchar(32) DEFAULT NULL,
  `provider_code` varchar(64) DEFAULT NULL,
  `model_name` varchar(128) DEFAULT NULL,
  `result_status` varchar(32) NOT NULL,
  `error_code` int DEFAULT NULL,
  `prompt_tokens` int NOT NULL DEFAULT 0,
  `completion_tokens` int NOT NULL DEFAULT 0,
  `input_bytes` bigint NOT NULL DEFAULT 0,
  `output_bytes` bigint NOT NULL DEFAULT 0,
  `latency_ms` bigint NOT NULL DEFAULT 0,
  `completed_at` datetime DEFAULT NULL,
  `tenant_id` varchar(64) NOT NULL,
  `org_id` bigint DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` bigint DEFAULT NULL,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_audit_tenant_request` (`tenant_id`, `request_id`),
  KEY `idx_ai_audit_tenant_time` (`tenant_id`, `created_at`),
  KEY `idx_ai_audit_tenant_service` (`tenant_id`, `service_code`, `created_at`),
  KEY `idx_ai_audit_tenant_status` (`tenant_id`, `result_status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租户级 AI 服务调用审计与用量';
