-- Authorization schema baseline.
-- Flyway owns DDL only; required and demo data are declared under META-INF/mango/resources.

CREATE TABLE IF NOT EXISTS `authorization_api_resource` (
  `id` bigint NOT NULL COMMENT '主键',
  `module_name` varchar(128) NOT NULL COMMENT '稳定模块名',
  `http_method` varchar(16) NOT NULL COMMENT 'HTTP 方法',
  `path_pattern` varchar(512) NOT NULL COMMENT '接口路径模式',
  `resource_code` varchar(640) NOT NULL COMMENT '资源编码',
  `permission_code` varchar(255) DEFAULT NULL COMMENT '权限编码',
  `access_mode` varchar(32) NOT NULL DEFAULT 'LOGIN' COMMENT '访问模式: PUBLIC/LOGIN/PERMISSION/INTERNAL',
  `handler_class` varchar(512) DEFAULT NULL COMMENT '处理类',
  `handler_method` varchar(128) DEFAULT NULL COMMENT '处理方法',
  `description` varchar(255) DEFAULT NULL COMMENT '描述',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-禁用, 1-启用',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记: 0-正常, 1-已删除',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_api_resource_method_path` (`module_name`,`http_method`,`path_pattern`),
  KEY `idx_authorization_api_resource_module` (`module_name`),
  KEY `idx_authorization_api_resource_code` (`resource_code`),
  KEY `idx_authorization_api_resource_permission` (`permission_code`),
  KEY `idx_authorization_api_resource_access` (`access_mode`),
  KEY `idx_authorization_api_resource_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='接口资源表';

CREATE TABLE IF NOT EXISTS `authorization_app` (
  `id` bigint NOT NULL COMMENT '主键',
  `app_code` varchar(64) NOT NULL COMMENT '应用编码',
  `app_name` varchar(100) NOT NULL COMMENT '应用名称',
  `realm` varchar(32) DEFAULT NULL COMMENT '已迁移至 authorization_app_login_context.realm',
  `actor_type` varchar(32) DEFAULT NULL COMMENT '已迁移至 authorization_app_login_context.actor_type',
  `icon` varchar(64) DEFAULT NULL COMMENT '应用图标',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-禁用, 1-启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_app_code` (`app_code`),
  KEY `idx_authorization_app_realm` (`realm`),
  KEY `idx_authorization_app_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='授权应用入口表';

CREATE TABLE IF NOT EXISTS `authorization_app_login_context` (
  `id` bigint NOT NULL COMMENT '主键',
  `app_id` bigint NOT NULL COMMENT '应用ID',
  `app_code` varchar(64) NOT NULL COMMENT '应用编码',
  `realm` varchar(32) NOT NULL COMMENT '登录域',
  `actor_type` varchar(32) NOT NULL COMMENT '操作者类型',
  `default_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否默认上下文: 0-否, 1-是',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-禁用, 1-启用',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_app_context` (`app_code`,`realm`,`actor_type`),
  KEY `idx_authorization_app_context_app_id` (`app_id`),
  KEY `idx_authorization_app_context_realm` (`realm`),
  KEY `idx_authorization_app_context_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='授权应用登录上下文表';

CREATE TABLE IF NOT EXISTS `authorization_app_module` (
  `id` bigint NOT NULL COMMENT '主键',
  `app_code` varchar(64) NOT NULL COMMENT '逻辑应用编码',
  `module_code` varchar(128) NOT NULL COMMENT '能力模块编码',
  `module_name` varchar(128) NOT NULL COMMENT '能力模块名称',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-停用, 1-启用',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_app_module` (`app_code`,`module_code`),
  KEY `idx_authorization_app_module_app` (`app_code`),
  KEY `idx_authorization_app_module_module` (`module_code`),
  KEY `idx_authorization_app_module_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='逻辑应用集成能力模块表';

CREATE TABLE IF NOT EXISTS `authorization_frontend_app_registry` (
  `id` bigint NOT NULL COMMENT '前端入口注册ID',
  `app_code` varchar(64) NOT NULL COMMENT '授权应用编码',
  `app_type` varchar(32) NOT NULL DEFAULT 'LOCAL' COMMENT '前端入口类型: LOCAL/MICRO_APP/IFRAME/EXTERNAL_LINK',
  `deploy_mode` varchar(32) NOT NULL DEFAULT 'EMBEDDED' COMMENT '部署模式: EMBEDDED/REMOTE/HYBRID',
  `entry_url` varchar(500) DEFAULT NULL COMMENT '远程入口地址',
  `mount_path` varchar(255) DEFAULT NULL COMMENT '主框架挂载路径',
  `active_rule` varchar(255) DEFAULT NULL COMMENT '激活规则',
  `framework` varchar(64) DEFAULT NULL COMMENT '前端运行框架',
  `version` varchar(64) DEFAULT NULL COMMENT '当前版本',
  `health_check_url` varchar(500) DEFAULT NULL COMMENT '健康检查地址',
  `sandbox_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否启用沙箱',
  `style_isolation` varchar(32) NOT NULL DEFAULT 'NONE' COMMENT '样式隔离: NONE/SCOPED/SHADOW_DOM/IFRAME',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_frontend_app_registry_app_code` (`app_code`),
  KEY `idx_authorization_frontend_app_registry_type` (`app_type`),
  KEY `idx_authorization_frontend_app_registry_mount_path` (`mount_path`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='前端应用入口注册表';

CREATE TABLE IF NOT EXISTS `authorization_frontend_module_runtime_strategy` (
  `id` bigint NOT NULL COMMENT '模块运行策略ID',
  `app_code` varchar(64) NOT NULL COMMENT '逻辑应用编码',
  `module_code` varchar(128) NOT NULL COMMENT '能力模块编码',
  `deploy_profile` varchar(32) NOT NULL DEFAULT 'monolith' COMMENT '部署配置档: monolith/hybrid/micro',
  `page_type` varchar(32) NOT NULL DEFAULT 'LOCAL_ROUTE' COMMENT '页面运行类型: LOCAL_ROUTE/MICRO_ROUTE/IFRAME/EXTERNAL_LINK',
  `runtime_code` varchar(64) NOT NULL COMMENT '前端运行单元编码，关联 authorization_frontend_app_registry.app_code',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-停用, 1-启用',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_frontend_module_runtime_strategy` (`app_code`,`module_code`,`deploy_profile`),
  KEY `idx_authorization_frontend_module_runtime_strategy_app` (`app_code`),
  KEY `idx_authorization_frontend_module_runtime_strategy_runtime` (`runtime_code`),
  KEY `idx_authorization_frontend_module_runtime_strategy_profile` (`deploy_profile`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='前端模块运行策略表';

CREATE TABLE IF NOT EXISTS `authorization_menu` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户ID',
  `app_code` varchar(64) NOT NULL DEFAULT 'internal-admin' COMMENT '应用编码',
  `module_code` varchar(128) NOT NULL DEFAULT 'mango-system' COMMENT '能力模块编码',
  `parent_id` bigint NOT NULL DEFAULT '0' COMMENT '父菜单ID',
  `menu_type` tinyint NOT NULL DEFAULT '1' COMMENT '菜单类型: 1-目录, 2-菜单, 3-按钮',
  `menu_name` varchar(64) NOT NULL COMMENT '菜单名称',
  `menu_code` varchar(128) DEFAULT NULL COMMENT '菜单权限标识',
  `path` varchar(255) DEFAULT NULL COMMENT '前端路由路径',
  `icon` varchar(64) DEFAULT NULL COMMENT '菜单图标',
  `component` varchar(255) DEFAULT NULL COMMENT '前端组件路径',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-禁用, 1-启用',
  `visible` tinyint NOT NULL DEFAULT '1' COMMENT '是否显示: 0-隐藏, 1-显示',
  `keep_alive` tinyint NOT NULL DEFAULT '0' COMMENT '路由缓存: 0-不缓存, 1-缓存',
  `embedded` tinyint NOT NULL DEFAULT '0' COMMENT '内嵌模式: 0-否, 1-iframe内嵌',
  `redirect` varchar(255) DEFAULT NULL COMMENT '重定向路径',
  `permissions` varchar(500) DEFAULT NULL COMMENT '权限标识列表',
  `api_codes` varchar(2000) DEFAULT NULL COMMENT '菜单携带的接口/动作权限码列表',
  `button_type` varchar(32) DEFAULT NULL COMMENT '按钮类型：TABLE-表格按钮，NON_TABLE-非表格按钮',
  `button_display_rule` varchar(1000) DEFAULT NULL COMMENT '按钮展示规则表达式',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(64) DEFAULT NULL COMMENT '修改人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记: 0-正常, 1-已删除',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  KEY `idx_authorization_menu_parent_id` (`parent_id`),
  KEY `idx_authorization_menu_app_parent` (`app_code`,`parent_id`),
  KEY `idx_authorization_menu_type` (`menu_type`),
  KEY `idx_authorization_menu_status` (`status`),
  KEY `idx_authorization_menu_del_flag` (`del_flag`),
  KEY `idx_authorization_menu_module_code` (`module_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜单表';

CREATE TABLE IF NOT EXISTS `authorization_menu_package` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户ID',
  `package_name` varchar(100) NOT NULL COMMENT '套餐名称',
  `package_code` varchar(64) NOT NULL COMMENT '套餐编码',
  `app_code` varchar(64) NOT NULL COMMENT '应用编码',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态:0-禁用,1-启用',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(64) DEFAULT NULL COMMENT '修改人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记: 0-正常, 1-已删除',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_menu_package_code` (`tenant_id`,`package_code`),
  KEY `idx_authorization_menu_package_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜单授权套餐主档';

CREATE TABLE IF NOT EXISTS `authorization_menu_package_item` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户ID',
  `package_id` bigint NOT NULL COMMENT '套餐ID',
  `menu_id` bigint NOT NULL COMMENT '菜单ID',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_menu_package_item` (`tenant_id`,`package_id`,`menu_id`),
  KEY `idx_authorization_menu_package_item_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜单授权套餐-菜单关联表';

CREATE TABLE IF NOT EXISTS `authorization_permission` (
  `id` bigint NOT NULL COMMENT '主键',
  `perm_code` varchar(100) NOT NULL COMMENT '权限码，格式 model:module:action',
  `perm_name` varchar(50) NOT NULL COMMENT '权限名称',
  `perm_type` varchar(20) NOT NULL DEFAULT 'MENU' COMMENT '类型：MENU/BUTTON/API',
  `module` varchar(50) NOT NULL COMMENT '所属模块',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-禁用 1-启用',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  UNIQUE KEY `perm_code` (`perm_code`),
  KEY `idx_authorization_permission_module` (`module`),
  KEY `idx_authorization_permission_type` (`perm_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='权限定义表';

CREATE TABLE IF NOT EXISTS `authorization_role` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户ID',
  `app_code` varchar(64) NOT NULL DEFAULT 'internal-admin' COMMENT '应用编码',
  `realm` varchar(32) NOT NULL DEFAULT 'INTERNAL' COMMENT '登录域',
  `actor_type` varchar(32) DEFAULT NULL COMMENT '操作者类型',
  `role_code` varchar(100) NOT NULL COMMENT '角色标识',
  `role_name` varchar(50) NOT NULL COMMENT '角色名称',
  `role_type` tinyint NOT NULL DEFAULT '1' COMMENT '角色类型: 1-系统角色 2-业务角色',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-禁用 1-启用',
  `sort` int NOT NULL DEFAULT '0' COMMENT '显示顺序',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_role_tenant_app_role_code` (`tenant_id`,`app_code`,`role_code`),
  KEY `idx_authorization_role_tenant_id` (`tenant_id`),
  KEY `idx_authorization_role_app_code` (`app_code`),
  KEY `idx_authorization_role_realm_actor` (`realm`,`actor_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色表';

CREATE TABLE IF NOT EXISTS `authorization_role_data_scope` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户ID',
  `app_code` varchar(64) NOT NULL DEFAULT 'internal-admin' COMMENT '应用编码',
  `role_id` bigint NOT NULL COMMENT '角色ID',
  `resource_code` varchar(128) NOT NULL COMMENT '资源编码',
  `scope_mode` varchar(32) NOT NULL DEFAULT 'SELF' COMMENT '数据范围模式: ALL/SELF/SELF_ORG/SELF_ORG_AND_CHILDREN/ORG',
  `scope_values` json DEFAULT NULL COMMENT '范围值 JSON 数组',
  `include_children` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否包含下级组织',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-禁用, 1-启用',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_role_data_scope_role_resource` (`tenant_id`,`app_code`,`role_id`,`resource_code`),
  KEY `idx_authorization_role_data_scope_role` (`role_id`),
  KEY `idx_authorization_role_data_scope_resource` (`tenant_id`,`app_code`,`resource_code`),
  KEY `idx_authorization_role_data_scope_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色数据权限配置表';

CREATE TABLE IF NOT EXISTS `authorization_role_menu` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户ID',
  `role_id` bigint NOT NULL COMMENT '角色ID',
  `menu_id` bigint NOT NULL COMMENT '菜单ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  KEY `idx_authorization_role_menu_role_id` (`role_id`),
  KEY `idx_authorization_role_menu_menu_id` (`menu_id`),
  KEY `idx_authorization_role_menu_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色菜单关联表';

CREATE TABLE IF NOT EXISTS `authorization_role_permission` (
  `id` bigint NOT NULL COMMENT '主键',
  `role_id` bigint NOT NULL COMMENT '角色ID',
  `perm_id` bigint NOT NULL COMMENT '权限ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_role_permission_role_perm` (`role_id`,`perm_id`),
  KEY `idx_authorization_role_permission_role_id` (`role_id`),
  KEY `idx_authorization_role_permission_perm_id` (`perm_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色权限关联表';

CREATE TABLE IF NOT EXISTS `authorization_subject_permission` (
  `id` bigint NOT NULL COMMENT '主键',
  `subject_id` bigint NOT NULL COMMENT '主体ID',
  `perm_id` bigint NOT NULL COMMENT '权限ID',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_subject_permission_subject_perm` (`subject_id`,`perm_id`,`tenant_id`),
  KEY `idx_authorization_subject_permission_subject_id` (`subject_id`),
  KEY `idx_authorization_subject_permission_perm_id` (`perm_id`),
  KEY `idx_authorization_subject_permission_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='主体直授权限表';

CREATE TABLE IF NOT EXISTS `authorization_subject_role` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户ID',
  `subject_id` bigint NOT NULL COMMENT '主体ID',
  `subject_type` varchar(32) NOT NULL DEFAULT 'TENANT_MEMBER' COMMENT '主体类型',
  `app_code` varchar(64) DEFAULT NULL COMMENT '应用编码',
  `realm` varchar(32) DEFAULT NULL COMMENT '登录域',
  `actor_type` varchar(32) DEFAULT NULL COMMENT '操作者类型',
  `party_type` varchar(64) DEFAULT NULL COMMENT '归属主体类型',
  `party_id` bigint DEFAULT NULL COMMENT '归属主体ID',
  `role_id` bigint NOT NULL COMMENT '角色ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authorization_subject_role_subject_role` (`subject_type`,`subject_id`,`role_id`,`tenant_id`,`app_code`,`party_type`,`party_id`),
  KEY `idx_authorization_subject_role_role_id` (`role_id`),
  KEY `idx_authorization_subject_role_tenant_id` (`tenant_id`),
  KEY `idx_authorization_subject_role_context` (`subject_type`,`subject_id`,`app_code`,`realm`,`party_type`,`party_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='主体角色关联表';

CREATE TABLE IF NOT EXISTS `frontend_menu_runtime_config` (
  `id` bigint NOT NULL COMMENT '菜单运行配置ID',
  `menu_id` bigint NOT NULL COMMENT '授权菜单ID',
  `app_code` varchar(64) NOT NULL COMMENT '授权应用编码',
  `page_type` varchar(32) NOT NULL DEFAULT 'LOCAL_ROUTE' COMMENT '页面运行类型: LOCAL_ROUTE/MICRO_ROUTE/IFRAME/EXTERNAL_LINK/BUTTON',
  `external_url` varchar(500) DEFAULT NULL COMMENT 'iframe 或外链地址',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_frontend_menu_runtime_menu_id` (`menu_id`),
  KEY `idx_frontend_menu_runtime_app_code` (`app_code`),
  KEY `idx_frontend_menu_runtime_page_type` (`page_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='前端菜单运行配置表';

CREATE TABLE IF NOT EXISTS `frontend_tenant_app_binding` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` bigint NOT NULL COMMENT '租户 ID',
  `app_code` varchar(64) NOT NULL COMMENT '前端入口所属授权应用编码',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-停用, 1-启用',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `org_id` bigint DEFAULT NULL COMMENT '组织标识',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_frontend_tenant_app_binding` (`tenant_id`,`app_code`),
  KEY `idx_frontend_tenant_app_binding_app_code` (`app_code`),
  KEY `idx_frontend_tenant_app_binding_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='前端租户应用开通关系表';
