package io.mango.file.core.resource;

import com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration;
import io.mango.file.core.config.FileProperties;
import io.mango.file.core.mapper.FileObjectMapper;
import io.mango.file.core.mapper.FileRecordMapper;
import io.mango.file.core.mapper.FileStorageConfigMapper;
import io.mango.file.core.storage.FileStorageRouter;
import io.mango.file.core.storage.LocalFileStorage;
import io.mango.infra.persistence.starter.PersistenceMybatisPlusAutoConfiguration;
import io.mango.resource.support.ResourceTypes;
import io.mango.resource.support.builder.ResourceDeclarationBuilder;
import io.mango.resource.support.model.ResourceDeclaration;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration;
import org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.HexFormat;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@SpringBootTest(classes = {
        DataSourceAutoConfiguration.class,
        JdbcTemplateAutoConfiguration.class,
        TransactionAutoConfiguration.class,
        MybatisPlusAutoConfiguration.class,
        PersistenceMybatisPlusAutoConfiguration.class,
        FileAssetResourceHandlerIntegrationTest.TestConfig.class
})
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:file_asset_handler;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.flyway.enabled=false",
        "mango.persistence.mybatis-plus.tenant.enabled=false"
})
class FileAssetResourceHandlerIntegrationTest {

    private static final long FILE_ID = 900000000000101L;
    private static final long STORAGE_CONFIG_ID = 101L;
    private static final String OBJECT_NAME = "mango-assets/integration/sample.txt";

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private FileAssetResourceHandler handler;

    @Autowired
    private FileProperties fileProperties;

    @TempDir
    Path temporaryDirectory;

    @BeforeEach
    void setUp() throws Exception {
        jdbcTemplate.execute("drop table if exists file_record");
        jdbcTemplate.execute("drop table if exists file_object");
        jdbcTemplate.execute("drop table if exists file_storage_config");
        jdbcTemplate.execute("""
                create table file_storage_config (
                    id bigint not null primary key, tenant_id bigint, org_id bigint,
                    config_name varchar(64), storage_type varchar(32), endpoint varchar(255),
                    public_endpoint varchar(255), region varchar(64), bucket_name varchar(128),
                    storage_path varchar(255), access_key varchar(255), secret_key varchar(512),
                    path_style_access int, ssl_enabled int, active int, status int, remark varchar(255),
                    created_by bigint, created_time timestamp, created_at timestamp,
                    updated_by bigint, updated_time timestamp, updated_at timestamp
                )
                """);
        jdbcTemplate.execute("""
                create table file_object (
                    id bigint generated by default as identity primary key, tenant_id bigint, org_id bigint,
                    storage_config_id bigint, storage_type varchar(32), bucket_name varchar(128),
                    object_name varchar(500), file_hash varchar(128), file_size bigint, content_type varchar(128),
                    status int, ref_count bigint, created_by bigint, created_time timestamp, created_at timestamp,
                    updated_by bigint, updated_time timestamp, updated_at timestamp
                )
                """);
        jdbcTemplate.execute("""
                create table file_record (
                    id bigint not null primary key, tenant_id bigint, org_id bigint,
                    biz_type varchar(64), biz_id varchar(128), purpose varchar(64), biz_meta varchar(2000),
                    directory_id bigint, access_level varchar(32), object_id bigint, storage_type varchar(32),
                    storage_config_id bigint, bucket_name varchar(128), object_name varchar(500),
                    file_name varchar(255), file_ext varchar(32), file_size bigint, content_type varchar(128),
                    file_hash varchar(128), status int, archived int, created_by bigint, created_time timestamp,
                    created_at timestamp, updated_by bigint, updated_time timestamp, updated_at timestamp
                )
                """);
        jdbcTemplate.update("""
                insert into file_storage_config (id, tenant_id, config_name, storage_type, bucket_name, status)
                values (?, ?, ?, ?, ?, ?)
                """, STORAGE_CONFIG_ID, "1", "integration", "LOCAL", "integration-bucket", 1);
        Path asset = temporaryDirectory.resolve("documents/sample.txt");
        Files.createDirectories(asset.getParent());
        Files.writeString(asset, "integration-asset\n", StandardCharsets.UTF_8);
        fileProperties.setAssetRoot(temporaryDirectory.toString());
        fileProperties.getLocal().setRootPath(temporaryDirectory.toString());
    }

    @Test
    void publishesExternalAssetThroughRealMappersAndTransaction() throws Exception {
        String sha256 = HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256")
                .digest("integration-asset\n".getBytes(StandardCharsets.UTF_8)));
        ResourceDeclaration declaration = declaration("asset:documents/sample.txt", sha256);

        handler.upsert(declaration);
        handler.upsert(declaration);

        assertThat(jdbcTemplate.queryForObject("select count(*) from file_record", Integer.class)).isOne();
        assertThat(jdbcTemplate.queryForObject("select count(*) from file_object", Integer.class)).isOne();
        assertThat(jdbcTemplate.queryForObject("select file_hash from file_record where id = ?", String.class,
                FILE_ID)).isEqualTo(sha256);
        assertThat(Files.readString(temporaryDirectory.resolve("integration-bucket/" + OBJECT_NAME)))
                .isEqualTo("integration-asset\n");
    }

    @Test
    void rejectsUnsafeExternalAssetBeforeDatabaseWrite() {
        ResourceDeclaration declaration = declaration("asset:../outside.txt", "0".repeat(64));

        assertThatThrownBy(() -> handler.upsert(declaration))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("safe relative path");
        assertThat(jdbcTemplate.queryForObject("select count(*) from file_record", Integer.class)).isZero();
        assertThat(jdbcTemplate.queryForObject("select count(*) from file_object", Integer.class)).isZero();
    }

    private ResourceDeclaration declaration(String location, String sha256) {
        return ResourceDeclarationBuilder.create(ResourceTypes.FILE_ASSET)
                .id("integration.file-asset")
                .version(1)
                .bizKey("integration.file-asset")
                .longValue("tenantId", 1L)
                .longValue("fileId", FILE_ID)
                .longValue("storageConfigId", STORAGE_CONFIG_ID)
                .string("objectName", OBJECT_NAME)
                .string("fileName", "sample.txt")
                .string("sha256", sha256)
                .file("content", location, null, "text/plain")
                .build();
    }

    @Configuration
    @Import(FileAssetResourceHandler.class)
    @MapperScan(basePackageClasses = FileStorageConfigMapper.class)
    static class TestConfig {

        @Bean
        FileProperties fileProperties() {
            return new FileProperties();
        }

        @Bean
        LocalFileStorage localFileStorage(FileProperties properties) {
            return new LocalFileStorage(properties);
        }

        @Bean
        FileStorageRouter fileStorageRouter(LocalFileStorage storage) {
            return new FileStorageRouter(java.util.List.of(storage));
        }
    }
}
