export { default as LoginView } from './views/login.vue';
export { default as ProfileView } from './views/profile.vue';
export { default as PasswordView } from './views/password.vue';
export { default as ProviderCallbackView } from './views/provider-callback.vue';
export { default as ProviderConfigView } from './views/provider-config.vue';
export * from './config';
export * from './store/userInfo';
export * from './api/sys';
export * from './api/identity';
export * from './api/provider';
export * from './composables/useMangoLoginFlow';
