package io.mango.notice.api.enums;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "通知发送失败码")
public enum NoticeFailureCode {
    CHANNEL_UNAVAILABLE,
    CHANNEL_DISABLED,
    CHANNEL_CONFIG_INVALID,
    CHANNEL_ROUTE_INVALID,
    CHANNEL_ROUTE_TAG_UNAVAILABLE,
    TEMPLATE_INVALID,
    RECIPIENT_INVALID,
    PROVIDER_REJECTED,
    PROVIDER_TIMEOUT,
    PROVIDER_ERROR,
    ATTACHMENT_PROVIDER_UNAVAILABLE,
    ATTACHMENT_NOT_FOUND_OR_FORBIDDEN,
    ATTACHMENT_LIMIT_EXCEEDED,
    ATTACHMENT_TYPE_NOT_ALLOWED,
    ATTACHMENT_READ_TIMEOUT,
    ATTACHMENT_READ_FAILED,
    RATE_LIMITED,
    SEND_EXCEPTION
}
