export { default as DictView } from './views/dict/index.vue';
export { default as OperationLogView } from './views/operation-log/index.vue';
export { default as LoginLogView } from './views/login-log/index.vue';
export { default as TenantView } from './views/tenant/index.vue';
export { default as ConfigView } from './views/config/index.vue';
export { default as RouteView } from './views/route/index.vue';
export { default as PublicPathView } from './views/public-path/index.vue';
export { default as AreaView } from './views/area/index.vue';
export { default as TemplateView } from './views/template/index.vue';
export { default as TemplateCategoryView } from './views/template/categories/index.vue';
export { default as TemplateServiceGuideView } from './views/platform-capabilities/template/index.vue';

export * from './api/area';
export * from './api/dict';
export * from './api/log';
export * from './api/tenant';
export * from './api/config';
export * from './api/route';
export * from './api/publicPath';
export * from './api/param';
export * from './api/template';
