export const componentsMap: Record<string, any> = {
  'system/menu/index': () => import('@mango/rbac').then(m => m.MenuView),
  'system/role/index': () => import('@mango/rbac').then(m => m.RoleView),
  'system/user/index': () => import('@mango/rbac').then(m => m.UserView),
  'system/org/index': () => import('@mango/rbac').then(m => m.OrgView),
  'system/permission/index': () => import('@mango/rbac').then(m => m.PermissionView),
  'system/app/index': () => import('@mango/rbac').then(m => m.AppView),
  'system/post/index': () => import('@mango/rbac').then(m => m.PostView),
  'views/system/menu/index': () => import('@mango/rbac').then(m => m.MenuView),
  'views/system/role/index': () => import('@mango/rbac').then(m => m.RoleView),
  'views/system/user/index': () => import('@mango/rbac').then(m => m.UserView),
  'views/system/org/index': () => import('@mango/rbac').then(m => m.OrgView),
  'views/system/permission/index': () => import('@mango/rbac').then(m => m.PermissionView),
  'views/system/app/index': () => import('@mango/rbac').then(m => m.AppView),
  'views/system/post/index': () => import('@mango/rbac').then(m => m.PostView),
  
  'system/dict/index': () => import('@mango/system').then(m => m.DictView),
  'system/operation-log/index': () => import('@mango/system').then(m => m.OperationLogView),
  'system/login-log/index': () => import('@mango/system').then(m => m.LoginLogView),
  'system/tenant/index': () => import('@mango/system').then(m => m.TenantView),
  'system/config/index': () => import('@mango/system').then(m => m.ConfigView),
  'system/route/index': () => import('@mango/system').then(m => m.RouteView),
  'system/public-path/index': () => import('@mango/system').then(m => m.PublicPathView),
  'system/area/index': () => import('@mango/system').then(m => m.AreaView),
  'views/system/dict/index': () => import('@mango/system').then(m => m.DictView),
  'views/system/operation-log/index': () => import('@mango/system').then(m => m.OperationLogView),
  'views/system/login-log/index': () => import('@mango/system').then(m => m.LoginLogView),
  'views/system/tenant/index': () => import('@mango/system').then(m => m.TenantView),
  'views/system/config/index': () => import('@mango/system').then(m => m.ConfigView),
  'views/system/route/index': () => import('@mango/system').then(m => m.RouteView),
  'views/system/public-path/index': () => import('@mango/system').then(m => m.PublicPathView),
  'views/system/area/index': () => import('@mango/system').then(m => m.AreaView),
};
