server:
  port: ${MANGO_NOTICE_APP_PORT:18620}

spring:
  application:
    name: mango-notice-capability-app

mango:
  module:
    module-service:
      modules:
        mango-identity:
          service-name: mango-identity-capability-app
        mango-org:
          service-name: mango-org-capability-app
        mango-resource:
          service-name: mango-resource-capability-app
