CREATE TABLE IF NOT EXISTS `guarantee_case` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '业务单ID',
    `case_no` VARCHAR(64) NOT NULL COMMENT '业务单编号',
    `source_tenant_id` BIGINT NOT NULL COMMENT '来源机构ID',
    `title` VARCHAR(200) NOT NULL COMMENT '业务单标题',
    `applicant_name` VARCHAR(100) NOT NULL COMMENT '申请人名称',
    `beneficiary_name` VARCHAR(100) DEFAULT NULL COMMENT '受益人名称',
    `guarantee_type` VARCHAR(64) DEFAULT NULL COMMENT '保函类型编码',
    `amount` DECIMAL(18,2) NOT NULL COMMENT '保函金额',
    `currency` VARCHAR(16) NOT NULL DEFAULT 'CNY' COMMENT '币种编码',
    `expected_issue_date` DATE DEFAULT NULL COMMENT '期望出函日期',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-草稿，1-处理中，2-已完成，9-已取消',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `tenant_id` BIGINT NOT NULL COMMENT '机构隔离ID，与来源机构一致',
    `create_by` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `update_by` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0-正常，1-已删除',
    UNIQUE KEY `uk_guarantee_case_no` (`case_no`),
    KEY `idx_guarantee_case_source_tenant` (`source_tenant_id`),
    KEY `idx_guarantee_case_tenant_status` (`tenant_id`, `status`),
    KEY `idx_guarantee_case_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='保函业务单';

CREATE TABLE IF NOT EXISTS `guarantee_case_participant` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT '参与方ID',
    `case_id` BIGINT NOT NULL COMMENT '业务单ID',
    `participant_tenant_id` BIGINT NOT NULL COMMENT '参与机构ID',
    `participant_type` VARCHAR(64) NOT NULL COMMENT '参与方类型',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-停用，1-启用',
    `tenant_id` BIGINT NOT NULL COMMENT '记录创建机构ID',
    `create_by` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `update_by` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0-正常，1-已删除',
    UNIQUE KEY `uk_guarantee_case_participant` (`case_id`, `participant_tenant_id`, `participant_type`, `del_flag`),
    KEY `idx_guarantee_case_participant_tenant` (`participant_tenant_id`, `status`),
    KEY `idx_guarantee_case_participant_case` (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='保函业务参与方';
